/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { ArenaError } from "./arena-error.js";

/**
 * There is no transmitter with the transmitter ID.
 */
export type GetSsfTransmitterTransmitterIdNotFoundErrorData = {
  result?: operations.GetSsfTransmitterTransmitterIdNotFoundResult | undefined;
};

/**
 * There is no transmitter with the transmitter ID.
 */
export class GetSsfTransmitterTransmitterIdNotFoundError extends ArenaError {
  result?: operations.GetSsfTransmitterTransmitterIdNotFoundResult | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSsfTransmitterTransmitterIdNotFoundErrorData;

  constructor(
    err: GetSsfTransmitterTransmitterIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.result != null) this.result = err.result;

    this.name = "GetSsfTransmitterTransmitterIdNotFoundError";
  }
}

/** @internal */
export const GetSsfTransmitterTransmitterIdNotFoundError$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdNotFoundError, unknown> = z.pipe(
    z.object({
      result: types.optional(z.lazy(() =>
        operations.GetSsfTransmitterTransmitterIdNotFoundResult$inboundSchema
      )),
      request$: z.custom<Request>(x =>
        x instanceof Request
      ),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetSsfTransmitterTransmitterIdNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
