/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { ArenaError } from "./arena-error.js";

/**
 * An error response indicating the value of the `format` request parameter is not supported.
 *
 * @remarks
 */
export type GetOpenapiBadRequestErrorData = {
  result?: operations.GetOpenapiResult | undefined;
};

/**
 * An error response indicating the value of the `format` request parameter is not supported.
 *
 * @remarks
 */
export class GetOpenapiBadRequestError extends ArenaError {
  result?: operations.GetOpenapiResult | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetOpenapiBadRequestErrorData;

  constructor(
    err: GetOpenapiBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.result != null) this.result = err.result;

    this.name = "GetOpenapiBadRequestError";
  }
}

/** @internal */
export const GetOpenapiBadRequestError$inboundSchema: z.ZodMiniType<
  GetOpenapiBadRequestError,
  unknown
> = z.pipe(
  z.object({
    result: types.optional(
      z.lazy(() => operations.GetOpenapiResult$inboundSchema),
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetOpenapiBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
