/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { ArenaError } from "./arena-error.js";

/**
 * There is no transmitter with the transmitter ID, or there is no stream with the stream ID that belongs to the transmitter.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundErrorData =
  {
    result?:
      | operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundResult
      | undefined;
  };

/**
 * There is no transmitter with the transmitter ID, or there is no stream with the stream ID that belongs to the transmitter.
 *
 * @remarks
 */
export class PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundError
  extends ArenaError
{
  result?:
    | operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundResult
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundErrorData;

  constructor(
    err: PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.result != null) this.result = err.result;

    this.name =
      "PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundError";
  }
}

/**
 * A verification event cannot be registered because the stream is disabled.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestErrorData =
  {
    result?:
      | operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestResult
      | undefined;
  };

/**
 * A verification event cannot be registered because the stream is disabled.
 *
 * @remarks
 */
export class PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestError
  extends ArenaError
{
  result?:
    | operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestResult
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestErrorData;

  constructor(
    err: PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.result != null) this.result = err.result;

    this.name =
      "PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestError";
  }
}

/** @internal */
export const PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundError$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundError,
    unknown
  > = z.pipe(
    z.object({
      result: types.optional(z.lazy(() =>
        operations
          .PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundResult$inboundSchema
      )),
      request$: z.custom<Request>(x =>
        x instanceof Request
      ),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostSsfTransmitterTransmitterIdStreamStreamIdVerifyNotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestError$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestError,
    unknown
  > = z.pipe(
    z.object({
      result: types.optional(z.lazy(() =>
        operations
          .PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestResult$inboundSchema
      )),
      request$: z.custom<Request>(x =>
        x instanceof Request
      ),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostSsfTransmitterTransmitterIdStreamStreamIdVerifyBadRequestError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );
