/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { delegateStreamsCreate } from "../funcs/delegate-streams-create.js";
import { delegateStreamsDelete } from "../funcs/delegate-streams-delete.js";
import { delegateStreamsGet } from "../funcs/delegate-streams-get.js";
import { delegateStreamsPoll } from "../funcs/delegate-streams-poll.js";
import { delegateStreamsReplace } from "../funcs/delegate-streams-replace.js";
import { delegateStreamsUpdate } from "../funcs/delegate-streams-update.js";
import { delegateStreamsVerify } from "../funcs/delegate-streams-verify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DelegateStreams extends ClientSDK {
  /**
   * Stream Create (HTTP POST to the configuration endpoint)
   *
   * @remarks
   * This API processes a stream creation request, which is an HTTP POST request to the configuration endpoint of the transmitter.
   */
  async create(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamCreateRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamCreateResponseResponse
  > {
    return unwrapAsync(delegateStreamsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Read (HTTP GET to the configuration endpoint)
   *
   * @remarks
   * This API processes a stream read request, which is an HTTP GET request to the configuration endpoint of the transmitter.
   */
  async get(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse
  > {
    return unwrapAsync(delegateStreamsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Update (HTTP PATCH to the configuration endpoint)
   *
   * @remarks
   * This API processes a stream update request, which is an HTTP PATCH request to the configuration endpoint of the transmitter.
   */
  async update(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamUpdateRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamUpdateResponseResponse
  > {
    return unwrapAsync(delegateStreamsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Replace (HTTP PUT to the configuration endpoint)
   *
   * @remarks
   * This API processes a stream replace request, which is an HTTP PUT request to the configuration endpoint of the transmitter.
   */
  async replace(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamReplaceRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamReplaceResponseResponse
  > {
    return unwrapAsync(delegateStreamsReplace(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Delete (HTTP DELETE to the configuration endpoint)
   *
   * @remarks
   * This API processes a stream deletion request, which is an HTTP DELETE request to the configuration endpoint of the transmitter.
   */
  async delete(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse
  > {
    return unwrapAsync(delegateStreamsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Verify (HTTP POST to the verification endpoint)
   *
   * @remarks
   * This API processes a verification request, which is an HTTP POST request to the verification endpoint of the transmitter.
   */
  async verify(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamVerifyRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamVerifyResponseResponse
  > {
    return unwrapAsync(delegateStreamsVerify(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Poll (HTTP POST to the poll endpoint)
   *
   * @remarks
   * This API processes a poll request, which is an HTTP POST request to the poll endpoint of the transmitter.
   */
  async poll(
    request:
      operations.PostSsfTransmitterTransmitterIdDelegateStreamPollStreamIdRequestRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdDelegateStreamPollStreamIdResponseResponse
  > {
    return unwrapAsync(delegateStreamsPoll(
      this,
      request,
      options,
    ));
  }
}
