/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsDelete } from "../funcs/events-delete.js";
import { eventsGet } from "../funcs/events-get.js";
import { eventsList } from "../funcs/events-list.js";
import { eventsRegister } from "../funcs/events-register.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * Register an event.
   */
  async register(
    request: operations.PostSsfTransmitterTransmitterIdEventRegisterRequest,
    options?: RequestOptions,
  ): Promise<operations.PostSsfTransmitterTransmitterIdEventRegisterResponse> {
    return unwrapAsync(eventsRegister(
      this,
      request,
      options,
    ));
  }

  /**
   * List stream events.
   *
   * @remarks
   * This API returns the events that have been dispatched to the stream.
   *
   * Search criteria can be specified using query parameters when calling the
   * API. For example, if the
   * `event_identifier=https://schemas.openid.net/secevent/caep/event-type/session-revoked`
   * query parameter is provided, only events whose event identifier matches
   * the specified value are returned. Similarly, if the
   * `toe_ge=2026-01-01T12:00:00` query parameter is specified, only events
   * whose time of event (`toe`) is on or after "2026-01-01 12:00:00 (UTC)"
   * are returned. Multiple search criteria can be combined.
   *
   * The `limit` query parameter specifies the maximum number of events
   * included in the response. If this parameter is omitted, the default value
   * of `50` is used. The value of `limit` must be between `1` and `200`,
   * inclusive.
   *
   * If additional matching events remain, the API response includes the
   * `next_cursor` response parameter. By specifying its value as the `cursor`
   * query parameter in the next API call, you can retrieve the next page of
   * events starting from the position indicated by the cursor. Therefore, by
   * repeatedly calling the API with the `next_cursor` value returned in the
   * previous response as the value of the `cursor` query parameter, until the
   * response no longer contains `next_cursor`, you can retrieve all matching
   * events.
   *
   * If the `cursor` query parameter is included in an API call, all query
   * parameters that specify search criteria are ignored. The cursor preserves
   * the search criteria specified in the initial API call, so there is no need
   * to specify them again. Note, however, that the `limit` query parameter is
   * not considered a search criterion and can therefore be used together with
   * the `cursor` query parameter.
   */
  async list(
    request:
      operations.GetSsfTransmitterTransmitterIdStreamStreamIdEventListRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetSsfTransmitterTransmitterIdStreamStreamIdEventListResponse
  > {
    return unwrapAsync(eventsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve information about the event.
   */
  async get(
    request:
      operations.GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse
  > {
    return unwrapAsync(eventsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete the event.
   */
  async delete(
    request:
      operations.DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse
  > {
    return unwrapAsync(eventsDelete(
      this,
      request,
      options,
    ));
  }
}
