/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthDatabase } from "../funcs/health-database.js";
import { healthLiveness } from "../funcs/health-liveness.js";
import { healthReadiness } from "../funcs/health-readiness.js";
import { healthStartup } from "../funcs/health-startup.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Database probe.
   *
   * @remarks
   * This API is intended to check whether the database connection is alive or down.
   */
  async database(
    request?: operations.GetProbeDatabaseRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetProbeDatabaseResponse> {
    return unwrapAsync(healthDatabase(
      this,
      request,
      options,
    ));
  }

  /**
   * Liveness probe for Kubernetes.
   *
   * @remarks
   * This API is intended to serve as a Kubernetes liveness probe. Refer to [Liveness, Readiness, and Startup Probes](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/) for details.
   */
  async liveness(
    request?: operations.GetProbeLivenessRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetProbeLivenessResponse> {
    return unwrapAsync(healthLiveness(
      this,
      request,
      options,
    ));
  }

  /**
   * Readiness probe for Kubernetes.
   *
   * @remarks
   * This API is intended to serve as a Kubernetes readiness probe. Refer to [Liveness, Readiness, and Startup Probes](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/) for details.
   */
  async readiness(
    request?: operations.GetProbeReadinessRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetProbeReadinessResponse> {
    return unwrapAsync(healthReadiness(
      this,
      request,
      options,
    ));
  }

  /**
   * Startup probe for Kubernetes.
   *
   * @remarks
   * This API is intended to serve as a Kubernetes startup probe. Refer to [Liveness, Readiness, and Startup Probes](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/) for details.
   */
  async startup(
    request?: operations.GetProbeStartupRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetProbeStartupResponse> {
    return unwrapAsync(healthStartup(
      this,
      request,
      options,
    ));
  }
}
