/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamsDelete } from "../funcs/streams-delete.js";
import { streamsGet } from "../funcs/streams-get.js";
import { streamsList } from "../funcs/streams-list.js";
import { streamsVerify } from "../funcs/streams-verify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Streams extends ClientSDK {
  /**
   * List streams.
   *
   * @remarks
   * This API returns the streams that belong to the transmitter.
   *
   * Search criteria can be specified using query parameters when calling the
   * API. For example, if the `status=enabled` query parameter is provided, only
   * streams whose status is `enabled` are returned; streams whose status is
   * `paused` or `disabled` are excluded from the response. Similarly, if the
   * `created_at_ge=2026-01-01T12:00:00` query parameter is specified, only
   * streams created on or after "2026-01-01 12:00:00 (UTC)" are returned.
   * Multiple search criteria can be combined.
   *
   * The `limit` query parameter specifies the maximum number of streams
   * included in the response. If this parameter is omitted, the default value
   * of `50` is used. The value of `limit` must be between `1` and `200`,
   * inclusive.
   *
   * If additional matching streams remain, the API response includes the
   * `next_cursor` response parameter. By specifying its value as the `cursor`
   * query parameter in the next API call, you can retrieve the next page of
   * streams starting from the position indicated by the cursor. Therefore, by
   * repeatedly calling the API with the `next_cursor` value returned in the
   * previous response as the value of the `cursor` query parameter, until the
   * response no longer contains `next_cursor`, you can retrieve all matching
   * streams.
   *
   * If the `cursor` query parameter is included in an API call, all query
   * parameters that specify search criteria are ignored. The cursor preserves
   * the search criteria specified in the initial API call, so there is no need
   * to specify them again. Note, however, that the `limit` query parameter is
   * not considered a search criterion and can therefore be used together with
   * the `cursor` query parameter.
   */
  async list(
    request: operations.GetSsfTransmitterTransmitterIdStreamListRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSsfTransmitterTransmitterIdStreamListResponse> {
    return unwrapAsync(streamsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve information about the stream.
   */
  async get(
    request: operations.GetSsfTransmitterTransmitterIdStreamStreamIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSsfTransmitterTransmitterIdStreamStreamIdResponse> {
    return unwrapAsync(streamsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete the stream.
   */
  async delete(
    request: operations.DeleteSsfTransmitterTransmitterIdStreamStreamIdRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeleteSsfTransmitterTransmitterIdStreamStreamIdResponse
  > {
    return unwrapAsync(streamsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Register a verification event into the stream.
   *
   * @remarks
   * This API registers a verification event into the stream.
   */
  async verify(
    request:
      operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostSsfTransmitterTransmitterIdStreamStreamIdVerifyResponse
  > {
    return unwrapAsync(streamsVerify(
      this,
      request,
      options,
    ));
  }
}
