workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    arena-api:
        inputs:
            - location: registry.speakeasyapi.dev/authlete/sdk-workspace/arena-api
        overlays:
            - location: ./overlays/method-naming.yaml
        output: .speakeasy/out.openapi.yaml
    arena-api-spec:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/authlete/sdk-workspace/arena-api
targets:
    arena:
        target: typescript
        source: arena-api
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/authlete/sdk-workspace/arena-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
