/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest =
  {
    /**
     * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
     *
     * @remarks
     */
    xFapiInteractionId?: any | undefined;
    /**
     * The transmitter ID.
     *
     * @remarks
     */
    transmitterId: any;
    /**
     * The stream ID.
     *
     * @remarks
     */
    streamId: any;
    /**
     * The JTI of the event.
     *
     * @remarks
     */
    eventJti: any;
    /**
     * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
     *
     * @remarks
     */
    pretty?: any | undefined;
  };

export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus =
  {
    Success: "success",
    Failure: "failure",
    BadRequest: "bad_request",
    Unauthorized: "unauthorized",
    Forbidden: "forbidden",
    NotFound: "not_found",
    Conflict: "conflict",
    ServerError: "server_error",
    ServiceUnavailable: "service_unavailable",
  } as const;
export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus =
  OpenEnum<
    typeof DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus
  >;

export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult =
  {
    status?:
      | DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus
      | undefined;
    code?: any | undefined;
    message?: any | undefined;
  };

export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus =
  {
    Success: "success",
    Failure: "failure",
    BadRequest: "bad_request",
    Unauthorized: "unauthorized",
    Forbidden: "forbidden",
    NotFound: "not_found",
    Conflict: "conflict",
    ServerError: "server_error",
    ServiceUnavailable: "service_unavailable",
  } as const;
export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus =
  OpenEnum<
    typeof DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus
  >;

export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult =
  {
    status?:
      | DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus
      | undefined;
    code?: any | undefined;
    message?: any | undefined;
  };

/**
 * Successfully deleted the event.
 */
export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody =
  {
    result?:
      | DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult
      | undefined;
  };

export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody;
  };

/** @internal */
export type DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$Outbound =
  {
    "x-fapi-interaction-id"?: any | undefined;
    transmitter_id: any;
    stream_id: any;
    event_jti: any;
    pretty: any;
  };

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$outboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$Outbound,
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      transmitterId: z.any(),
      streamId: z.any(),
      eventJti: z.any(),
      pretty: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
        streamId: "stream_id",
        eventJti: "event_jti",
      });
    }),
  );

export function deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequestToJSON(
  deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest:
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest,
): string {
  return JSON.stringify(
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$outboundSchema
      .parse(
        deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest,
      ),
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus,
  );

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus,
    unknown
  > = openEnums.inboundSchema(
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus,
  );

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult,
    unknown
  > = z.object({
    status: types.optional(
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResultFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema
      ),
    ),
  });

export function deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse$inboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse' from JSON`,
  );
}
