/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteSsfTransmitterTransmitterIdRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: string | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: boolean | undefined;
  transmitterId: string;
};

export const DeleteSsfTransmitterTransmitterIdNotFoundStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type DeleteSsfTransmitterTransmitterIdNotFoundStatus = OpenEnum<
  typeof DeleteSsfTransmitterTransmitterIdNotFoundStatus
>;

export type DeleteSsfTransmitterTransmitterIdNotFoundResult = {
  status?: DeleteSsfTransmitterTransmitterIdNotFoundStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

export const DeleteSsfTransmitterTransmitterIdStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type DeleteSsfTransmitterTransmitterIdStatus = OpenEnum<
  typeof DeleteSsfTransmitterTransmitterIdStatus
>;

export type DeleteSsfTransmitterTransmitterIdResult = {
  status?: DeleteSsfTransmitterTransmitterIdStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * Successfully deleted the transmitter.
 */
export type DeleteSsfTransmitterTransmitterIdResponseBody = {
  result?: DeleteSsfTransmitterTransmitterIdResult | undefined;
};

export type DeleteSsfTransmitterTransmitterIdResponse = {
  headers: { [k: string]: Array<string> };
  result: DeleteSsfTransmitterTransmitterIdResponseBody;
};

/** @internal */
export type DeleteSsfTransmitterTransmitterIdRequest$Outbound = {
  "x-fapi-interaction-id"?: string | undefined;
  pretty: boolean;
  transmitter_id: string;
};

/** @internal */
export const DeleteSsfTransmitterTransmitterIdRequest$outboundSchema:
  z.ZodMiniType<
    DeleteSsfTransmitterTransmitterIdRequest$Outbound,
    DeleteSsfTransmitterTransmitterIdRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.string()),
      pretty: z._default(z.boolean(), false),
      transmitterId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function deleteSsfTransmitterTransmitterIdRequestToJSON(
  deleteSsfTransmitterTransmitterIdRequest:
    DeleteSsfTransmitterTransmitterIdRequest,
): string {
  return JSON.stringify(
    DeleteSsfTransmitterTransmitterIdRequest$outboundSchema.parse(
      deleteSsfTransmitterTransmitterIdRequest,
    ),
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdNotFoundStatus$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdNotFoundStatus, unknown> =
    openEnums.inboundSchema(DeleteSsfTransmitterTransmitterIdNotFoundStatus);

/** @internal */
export const DeleteSsfTransmitterTransmitterIdNotFoundResult$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdNotFoundResult, unknown> = z
    .object({
      status: types.optional(
        DeleteSsfTransmitterTransmitterIdNotFoundStatus$inboundSchema,
      ),
      code: types.optional(types.string()),
      message: types.optional(types.string()),
    });

export function deleteSsfTransmitterTransmitterIdNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdNotFoundResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdNotFoundResult' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdStatus$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdStatus, unknown> = openEnums
    .inboundSchema(DeleteSsfTransmitterTransmitterIdStatus);

/** @internal */
export const DeleteSsfTransmitterTransmitterIdResult$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdResult, unknown> = z.object({
    status: types.optional(
      DeleteSsfTransmitterTransmitterIdStatus$inboundSchema,
    ),
    code: types.optional(types.string()),
    message: types.optional(types.string()),
  });

export function deleteSsfTransmitterTransmitterIdResultFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdResult' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdResponseBody$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdResponseBody, unknown> = z
    .object({
      result: types.optional(
        z.lazy(() => DeleteSsfTransmitterTransmitterIdResult$inboundSchema),
      ),
    });

export function deleteSsfTransmitterTransmitterIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteSsfTransmitterTransmitterIdResponse$inboundSchema:
  z.ZodMiniType<DeleteSsfTransmitterTransmitterIdResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        DeleteSsfTransmitterTransmitterIdResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deleteSsfTransmitterTransmitterIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSsfTransmitterTransmitterIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSsfTransmitterTransmitterIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteSsfTransmitterTransmitterIdResponse' from JSON`,
  );
}
