/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetSsfTransmitterTransmitterIdRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: string | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: boolean | undefined;
  /**
   * The transmitter ID.
   *
   * @remarks
   */
  transmitterId: string;
};

export const GetSsfTransmitterTransmitterIdNotFoundStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetSsfTransmitterTransmitterIdNotFoundStatus = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdNotFoundStatus
>;

export type GetSsfTransmitterTransmitterIdNotFoundResult = {
  status?: GetSsfTransmitterTransmitterIdNotFoundStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

export const GetSsfTransmitterTransmitterIdStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetSsfTransmitterTransmitterIdStatus = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdStatus
>;

export type GetSsfTransmitterTransmitterIdResult = {
  status?: GetSsfTransmitterTransmitterIdStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * The creator of the transmitter.
 */
export type GetSsfTransmitterTransmitterIdCreator = {
  /**
   * The issuer of the access token.
   */
  iss?: string | undefined;
  /**
   * The subject of the access token.
   */
  sub?: string | undefined;
  /**
   * The client ID of the access token.
   */
  clientId?: string | undefined;
  /**
   * The identifier of the access token.
   */
  jti?: string | undefined;
  /**
   * The base64url-encoded SHA-256 hash of the access token.
   */
  hash?: string | undefined;
};

export type GetSsfTransmitterTransmitterIdAuthorizationScheme = {
  specUrn: string;
};

/**
 * OPTIONAL. A string indicating the default behavior of newly created streams. If present, the value MUST be either `"ALL"` or `"NONE"`. If not provided, the Transmitter behavior in this regard is unspecified.
 *
 * @remarks
 * - `"ALL"` indicates that any subjects that are appropriate for the
 *   stream are added to the stream by default. The Receiver MAY remove
 *   subjects from the stream via the `remove_subject_endpoint`, causing
 *   events for those subjects to _not_ be transmitted. The Receiver MAY
 *   re-add any subjects removed this way via the `add_subject_endpoint`.
 *
 * - `"NONE"` indicates that no subjects are added by default. The Receiver
 *   MAY add subjects to the stream via the `add_subject_endpoint`,
 *   causing only events for those subjects to be transmitted. The Receiver
 *   MAY remove subjects added this way via the `remove_subject_endpoint`.
 */
export const GetSsfTransmitterTransmitterIdDefaultSubjects = {
  All: "ALL",
  None: "NONE",
} as const;
/**
 * OPTIONAL. A string indicating the default behavior of newly created streams. If present, the value MUST be either `"ALL"` or `"NONE"`. If not provided, the Transmitter behavior in this regard is unspecified.
 *
 * @remarks
 * - `"ALL"` indicates that any subjects that are appropriate for the
 *   stream are added to the stream by default. The Receiver MAY remove
 *   subjects from the stream via the `remove_subject_endpoint`, causing
 *   events for those subjects to _not_ be transmitted. The Receiver MAY
 *   re-add any subjects removed this way via the `add_subject_endpoint`.
 *
 * - `"NONE"` indicates that no subjects are added by default. The Receiver
 *   MAY add subjects to the stream via the `add_subject_endpoint`,
 *   causing only events for those subjects to be transmitted. The Receiver
 *   MAY remove subjects added this way via the `remove_subject_endpoint`.
 */
export type GetSsfTransmitterTransmitterIdDefaultSubjects = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdDefaultSubjects
>;

/**
 * Transmitter Configuration Metadata defined in [OpenID Shared Signals Framework Specification 1.0](https://openid.net/specs/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdMetadata = {
  /**
   * OPTIONAL. A version identifying the implementer's draft or final specification implemented by the Transmitter. This includes the numerical portion of the spec version as described in the document [[NAMINGCONVENTION](https://openid.net/wg/resources/naming-and-contents-of-specifications/)].
   *
   * @remarks
   */
  specVersion?: string | undefined;
  /**
   * REQUIRED. URL using the `https` scheme with no query or fragment component that the Transmitter asserts as its Issuer Identifier. This MUST be identical to the `iss` claim value in Security Event Tokens issued from this Transmitter.
   *
   * @remarks
   */
  issuer: string;
  /**
   * OPTIONAL. URL of the Transmitter's JSON Web Key Set [[RFC7517](https://www.rfc-editor.org/rfc/rfc7517.html)] document. This contains the signing key(s) the Receiver uses to validate signatures from the Transmitter. This value MUST be specified if the Transmitter intends to generate signed JWTs. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  jwksUri?: string | undefined;
  /**
   * RECOMMENDED. List of supported delivery method URIs.
   *
   * @remarks
   */
  deliveryMethodsSupported?: Array<string> | undefined;
  /**
   * OPTIONAL. The URL of the Configuration Endpoint. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  configurationEndpoint?: string | undefined;
  /**
   * OPTIONAL. The URL of the Status Endpoint. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  statusEndpoint?: string | undefined;
  /**
   * OPTIONAL. The URL of the Add Subject Endpoint. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  addSubjectEndpoint?: string | undefined;
  /**
   * OPTIONAL. The URL of the Remove Subject Endpoint. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  removeSubjectEndpoint?: string | undefined;
  /**
   * OPTIONAL. The URL of the Verification Endpoint. If present, this URL MUST use HTTP over TLS [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html)].
   *
   * @remarks
   */
  verificationEndpoint?: string | undefined;
  /**
   * OPTIONAL. An array of member names in a Complex Subject which, if present in a Subject Member in an event, MUST be interpreted by a Receiver.
   *
   * @remarks
   */
  criticalSubjectMembers?: Array<string> | undefined;
  /**
   * OPTIONAL. An array of JSON objects that specify the supported authorization scheme properties. To enable seamless discovery of configurations, the service provider SHOULD, with the appropriate security considerations, make the `authorization_schemes` attribute publicly accessible without prior authentication.
   *
   * @remarks
   */
  authorizationSchemes?:
    | Array<GetSsfTransmitterTransmitterIdAuthorizationScheme>
    | undefined;
  /**
   * OPTIONAL. A string indicating the default behavior of newly created streams. If present, the value MUST be either `"ALL"` or `"NONE"`. If not provided, the Transmitter behavior in this regard is unspecified.
   *
   * @remarks
   * - `"ALL"` indicates that any subjects that are appropriate for the
   *   stream are added to the stream by default. The Receiver MAY remove
   *   subjects from the stream via the `remove_subject_endpoint`, causing
   *   events for those subjects to _not_ be transmitted. The Receiver MAY
   *   re-add any subjects removed this way via the `add_subject_endpoint`.
   *
   * - `"NONE"` indicates that no subjects are added by default. The Receiver
   *   MAY add subjects to the stream via the `add_subject_endpoint`,
   *   causing only events for those subjects to be transmitted. The Receiver
   *   MAY remove subjects added this way via the `remove_subject_endpoint`.
   */
  defaultSubjects: GetSsfTransmitterTransmitterIdDefaultSubjects;
};

/**
 * The HTTP authentication scheme.
 */
export const GetSsfTransmitterTransmitterIdScheme = {
  Basic: "Basic",
  Bearer: "Bearer",
  DPoP: "DPoP",
} as const;
/**
 * The HTTP authentication scheme.
 */
export type GetSsfTransmitterTransmitterIdScheme = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdScheme
>;

/**
 * Configuration for access token introspection ([RFC 7662](https://www.rfc-editor.org/rfc/rfc7662.html)).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdIntrospectionConfiguration = {
  /**
   * The HTTP authentication scheme.
   */
  scheme?: GetSsfTransmitterTransmitterIdScheme | undefined;
  /**
   * The user ID, required for the Basic Authentication.
   */
  userId?: string | undefined;
  /**
   * The password, required for the Basic Authentication.
   */
  password?: string | undefined;
  /**
   * The access token, required for the Bearer or DPoP Authentication.
   */
  accessToken?: string | undefined;
  /**
   * The identifier of the authorization server.
   */
  issuer: string;
};

export type GetSsfTransmitterTransmitterIdSettings = {
  /**
   * The name of this Transmitter
   */
  name?: string | undefined;
  /**
   * The description about this Transmitter
   */
  description?: string | undefined;
  /**
   * This boolean flag indicates whether FAPI 2.0 compliance is required.
   *
   * @remarks
   *
   * If this flag is set to `true`, the requirements defined in the
   * [FAPI 2.0 Security Profile](https://openid.net/specs/fapi-security-profile-2_0-final.html)
   * are enforced. One notable requirement is that access tokens must
   * be sender-constrained using either MTLS
   * ([RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html)) or DPoP
   * ([RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html)).
   */
  fapi2Compliant: boolean;
  /**
   * This boolean flag indicates whether access tokens must be
   *
   * @remarks
   * sender-constrained using the DPoP
   * ([RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html)) mechanism.
   */
  dpopRequired: boolean;
  /**
   * This boolean flag indicates whether DPoP proof JWTs must include the
   *
   * @remarks
   * `nonce` claim.
   *
   * If this flag is set to `true`, the DPoP proof JWT presented with a
   * DPoP-key-bound access token must include the `nonce` claim. Otherwise,
   * the server will return a `401 Unauthorized` response with the error
   * code `use_dpop_nonce` and a `DPoP-Nonce` header. If the client receives
   * this error, it must regenerate a DPoP proof JWT including the `nonce`
   * claim, using the nonce value specified in the `DPop-Nonce` header, and
   * retry the request.
   *
   * Also note that the nonce value expires periodically. This means that
   * the client will periodically receive a `401 Unauthorized` response
   * with the error code `invalid_dpop_proof` and a `DPoP-Nonce` header.
   * If the client receives this error, it must regenerate a DPoP proof JWT
   * including the `nonce` claim with the updated nonce value specified in
   * the `DPoP-Nonce` header and retry the request.
   *
   * See [RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html) for details
   * about the DPoP nonce.
   */
  dpopNonceRequired: boolean;
  /**
   * The maximum clock skew in seconds. This value is taken into account
   *
   * @remarks
   * when validating time-related properties, such as the expiration time
   * of an access token.
   *
   * Note that when FAPI 2.0 compliance is required (i.e., when the
   * `fapi2_compliant` flag is set to `true`), the maximum clock skew is
   * adjusted to ensure that it falls within the range of 10 to 60 seconds.
   */
  maxClockSkewSeconds?: number | undefined;
  /**
   * The list of authorization servers this Transmitter queries for access token information.
   *
   * @remarks
   */
  authorizationServers?: Array<string> | undefined;
  /**
   * The list of configurations for access token introspection.
   *
   * @remarks
   */
  introspectionConfigurations?:
    | Array<GetSsfTransmitterTransmitterIdIntrospectionConfiguration>
    | undefined;
  /**
   * OPTIONAL. An array of URIs identifying the set of events supported by the Transmitter for a Receiver. If omitted, Event Transmitters SHOULD make this set available to the Event Receiver via some other means (e.g. publishing it in online documentation).
   *
   * @remarks
   */
  eventsSupported?: Array<string> | undefined;
  /**
   * The default value of `min_verification_interval` in a Stream configuration.
   *
   * @remarks
   */
  minVerificationIntervalDefault?: number | undefined;
  /**
   * The default value of `inactivity_timeout` in a Stream configuration.
   *
   * @remarks
   */
  inactivityTimeoutDefault?: number | undefined;
  /**
   * OPTIONAL. The URL of the Poll Endpoint.
   *
   * @remarks
   *
   * If the receiver specifies the delivery method as POLL (`urn:ietf:rfc:8936`)
   * in the stream creation request, the value of this property is used as the
   * `endpoint_url`. If the property value contains `STREAM_ID`, it will be
   * replaced with the newly issued stream ID.
   */
  pollEndpoint?: string | undefined;
};

export type GetSsfTransmitterTransmitterIdTransmitter = {
  /**
   * The time at which the transmitter was created, in the format of `YYYY-MM-DDThh:mm:ss`.
   *
   * @remarks
   */
  createdAt?: Date | undefined;
  /**
   * The time at which the transmitter was updated, in the format of `YYYY-MM-DDThh:mm:ss`.
   *
   * @remarks
   */
  updatedAt?: Date | undefined;
  /**
   * The creator of the transmitter.
   */
  creator?: GetSsfTransmitterTransmitterIdCreator | undefined;
  /**
   * The Transmitter ID assigned by the Arena Core Server. The value has 240-bit entropy and is encoded in the base32hex format, resulting in a 48-character lowercase string.
   *
   * @remarks
   * Strictly speaking, since the first 10 bits of the data are overwritten to ensure that the resulting string always starts with `tr`, the actual entropy is 230 bits. The `tr` here denotes Transmitter.
   * The purpose of this process is to enable someone encountering a 48-character base32hex-encoded string beginning with `tr` to infer that it might be a Transmitter ID. Conversely, a random string not starting with `tr` can be identified as not being a Transmitter ID.
   */
  transmitterId?: string | undefined;
  /**
   * Transmitter Configuration Metadata defined in [OpenID Shared Signals Framework Specification 1.0](https://openid.net/specs/openid-sharedsignals-framework-1_0.html).
   *
   * @remarks
   */
  metadata: GetSsfTransmitterTransmitterIdMetadata;
  settings?: GetSsfTransmitterTransmitterIdSettings | undefined;
};

/**
 * Successfully retrieved information about the transmitter.
 */
export type GetSsfTransmitterTransmitterIdResponseBody = {
  result?: GetSsfTransmitterTransmitterIdResult | undefined;
  transmitter?: GetSsfTransmitterTransmitterIdTransmitter | undefined;
};

export type GetSsfTransmitterTransmitterIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetSsfTransmitterTransmitterIdResponseBody;
};

/** @internal */
export type GetSsfTransmitterTransmitterIdRequest$Outbound = {
  "x-fapi-interaction-id"?: string | undefined;
  pretty: boolean;
  transmitter_id: string;
};

/** @internal */
export const GetSsfTransmitterTransmitterIdRequest$outboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdRequest$Outbound,
    GetSsfTransmitterTransmitterIdRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.string()),
      pretty: z._default(z.boolean(), false),
      transmitterId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdRequestToJSON(
  getSsfTransmitterTransmitterIdRequest: GetSsfTransmitterTransmitterIdRequest,
): string {
  return JSON.stringify(
    GetSsfTransmitterTransmitterIdRequest$outboundSchema.parse(
      getSsfTransmitterTransmitterIdRequest,
    ),
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdNotFoundStatus$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdNotFoundStatus, unknown> =
    openEnums.inboundSchema(GetSsfTransmitterTransmitterIdNotFoundStatus);

/** @internal */
export const GetSsfTransmitterTransmitterIdNotFoundResult$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdNotFoundResult, unknown> = z
    .object({
      status: types.optional(
        GetSsfTransmitterTransmitterIdNotFoundStatus$inboundSchema,
      ),
      code: types.optional(types.string()),
      message: types.optional(types.string()),
    });

export function getSsfTransmitterTransmitterIdNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdNotFoundResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdNotFoundResult' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStatus$inboundSchema: z.ZodMiniType<
  GetSsfTransmitterTransmitterIdStatus,
  unknown
> = openEnums.inboundSchema(GetSsfTransmitterTransmitterIdStatus);

/** @internal */
export const GetSsfTransmitterTransmitterIdResult$inboundSchema: z.ZodMiniType<
  GetSsfTransmitterTransmitterIdResult,
  unknown
> = z.object({
  status: types.optional(GetSsfTransmitterTransmitterIdStatus$inboundSchema),
  code: types.optional(types.string()),
  message: types.optional(types.string()),
});

export function getSsfTransmitterTransmitterIdResultFromJSON(
  jsonString: string,
): SafeParseResult<GetSsfTransmitterTransmitterIdResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdResult' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdCreator$inboundSchema: z.ZodMiniType<
  GetSsfTransmitterTransmitterIdCreator,
  unknown
> = z.pipe(
  z.object({
    iss: types.optional(types.string()),
    sub: types.optional(types.string()),
    client_id: types.optional(types.string()),
    jti: types.optional(types.string()),
    hash: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "client_id": "clientId",
    });
  }),
);

export function getSsfTransmitterTransmitterIdCreatorFromJSON(
  jsonString: string,
): SafeParseResult<GetSsfTransmitterTransmitterIdCreator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdCreator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdCreator' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdAuthorizationScheme$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdAuthorizationScheme, unknown> = z
    .pipe(
      z.object({
        spec_urn: types.string(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "spec_urn": "specUrn",
        });
      }),
    );

export function getSsfTransmitterTransmitterIdAuthorizationSchemeFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdAuthorizationScheme,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdAuthorizationScheme$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdAuthorizationScheme' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdDefaultSubjects$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdDefaultSubjects, unknown> =
    openEnums.inboundSchema(GetSsfTransmitterTransmitterIdDefaultSubjects);

/** @internal */
export const GetSsfTransmitterTransmitterIdMetadata$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdMetadata, unknown> = z.pipe(
    z.object({
      spec_version: types.optional(types.string()),
      issuer: types.string(),
      jwks_uri: types.optional(types.string()),
      delivery_methods_supported: types.optional(z.array(types.string())),
      configuration_endpoint: types.optional(types.string()),
      status_endpoint: types.optional(types.string()),
      add_subject_endpoint: types.optional(types.string()),
      remove_subject_endpoint: types.optional(types.string()),
      verification_endpoint: types.optional(types.string()),
      critical_subject_members: types.optional(z.array(types.string())),
      authorization_schemes: types.optional(z.array(z.lazy(() =>
        GetSsfTransmitterTransmitterIdAuthorizationScheme$inboundSchema
      ))),
      default_subjects: z._default(
        GetSsfTransmitterTransmitterIdDefaultSubjects$inboundSchema,
        "NONE",
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "spec_version": "specVersion",
        "jwks_uri": "jwksUri",
        "delivery_methods_supported": "deliveryMethodsSupported",
        "configuration_endpoint": "configurationEndpoint",
        "status_endpoint": "statusEndpoint",
        "add_subject_endpoint": "addSubjectEndpoint",
        "remove_subject_endpoint": "removeSubjectEndpoint",
        "verification_endpoint": "verificationEndpoint",
        "critical_subject_members": "criticalSubjectMembers",
        "authorization_schemes": "authorizationSchemes",
        "default_subjects": "defaultSubjects",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetSsfTransmitterTransmitterIdMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdMetadata' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdScheme$inboundSchema: z.ZodMiniType<
  GetSsfTransmitterTransmitterIdScheme,
  unknown
> = openEnums.inboundSchema(GetSsfTransmitterTransmitterIdScheme);

/** @internal */
export const GetSsfTransmitterTransmitterIdIntrospectionConfiguration$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdIntrospectionConfiguration,
    unknown
  > = z.pipe(
    z.object({
      scheme: types.optional(
        GetSsfTransmitterTransmitterIdScheme$inboundSchema,
      ),
      user_id: types.optional(types.string()),
      password: types.optional(types.string()),
      access_token: types.optional(types.string()),
      issuer: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "user_id": "userId",
        "access_token": "accessToken",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdIntrospectionConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdIntrospectionConfiguration,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdIntrospectionConfiguration$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdIntrospectionConfiguration' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdSettings$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdSettings, unknown> = z.pipe(
    z.object({
      name: types.optional(types.string()),
      description: types.optional(types.string()),
      fapi2_compliant: z._default(types.boolean(), false),
      dpop_required: z._default(types.boolean(), false),
      dpop_nonce_required: z._default(types.boolean(), false),
      max_clock_skew_seconds: types.optional(types.number()),
      authorization_servers: types.optional(z.array(types.string())),
      introspection_configurations: types.optional(z.array(z.lazy(() =>
        GetSsfTransmitterTransmitterIdIntrospectionConfiguration$inboundSchema
      ))),
      events_supported: types.optional(z.array(types.string())),
      min_verification_interval_default: types.optional(types.number()),
      inactivity_timeout_default: types.optional(types.number()),
      poll_endpoint: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "fapi2_compliant": "fapi2Compliant",
        "dpop_required": "dpopRequired",
        "dpop_nonce_required": "dpopNonceRequired",
        "max_clock_skew_seconds": "maxClockSkewSeconds",
        "authorization_servers": "authorizationServers",
        "introspection_configurations": "introspectionConfigurations",
        "events_supported": "eventsSupported",
        "min_verification_interval_default": "minVerificationIntervalDefault",
        "inactivity_timeout_default": "inactivityTimeoutDefault",
        "poll_endpoint": "pollEndpoint",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdSettingsFromJSON(
  jsonString: string,
): SafeParseResult<GetSsfTransmitterTransmitterIdSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdSettings' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdTransmitter$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdTransmitter, unknown> = z.pipe(
    z.object({
      created_at: types.optional(types.date()),
      updated_at: types.optional(types.date()),
      creator: types.optional(z.lazy(() =>
        GetSsfTransmitterTransmitterIdCreator$inboundSchema
      )),
      transmitter_id: types.optional(types.string()),
      metadata: z.lazy(() =>
        GetSsfTransmitterTransmitterIdMetadata$inboundSchema
      ),
      settings: types.optional(z.lazy(() =>
        GetSsfTransmitterTransmitterIdSettings$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "updated_at": "updatedAt",
        "transmitter_id": "transmitterId",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdTransmitterFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdTransmitter,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdTransmitter$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdTransmitter' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdResponseBody$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdResponseBody, unknown> = z.object(
    {
      result: types.optional(z.lazy(() =>
        GetSsfTransmitterTransmitterIdResult$inboundSchema
      )),
      transmitter: types.optional(z.lazy(() =>
        GetSsfTransmitterTransmitterIdTransmitter$inboundSchema
      )),
    },
  );

export function getSsfTransmitterTransmitterIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdResponse$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetSsfTransmitterTransmitterIdResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSsfTransmitterTransmitterIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdResponse' from JSON`,
  );
}
