/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * This query parameter specifies the stream status as a search criterion.
 *
 * @remarks
 * The allowed values are `enabled`, `paused`, and `disabled`.
 */
export const QueryParamStatus = {
  Enabled: "enabled",
  Paused: "paused",
  Disabled: "disabled",
} as const;
/**
 * This query parameter specifies the stream status as a search criterion.
 *
 * @remarks
 * The allowed values are `enabled`, `paused`, and `disabled`.
 */
export type QueryParamStatus = ClosedEnum<typeof QueryParamStatus>;

export type GetSsfTransmitterTransmitterIdStreamListRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: any | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: any | undefined;
  /**
   * The transmitter ID.
   *
   * @remarks
   */
  transmitterId: any;
  /**
   * This query parameter specifies the starting position of the search. By
   *
   * @remarks
   * using the value of the `next_cursor` response parameter returned in the
   * previous API response as the value of this query parameter, you can
   * resume the search from where the previous API call left off. For details,
   * see the description of this API.
   */
  cursor?: any | undefined;
  /**
   * This query parameter specifies, as a search criterion, the ID of the
   *
   * @remarks
   * client application associated with the access token that was used to
   * create the stream.
   */
  clientId?: any | undefined;
  /**
   * This query parameter specifies the lower bound of the stream creation
   *
   * @remarks
   * time as a search criterion. Only streams created on or after the
   * specified date and time are included in the results. The following
   * value formats are accepted:
   *
   * - `YYYY-MM-DD`
   * - `YYYY-MM-DD[+-]hh:mm`
   * - `YYYY-MM-DDThh:mm`
   * - `YYYY-MM-DDThh:mmZ`
   * - `YYYY-MM-DDThh:mm[+-]hh:mm`
   * - `YYYY-MM-DDThh:mm:ss`
   * - `YYYY-MM-DDThh:mm:ssZ`
   * - `YYYY-MM-DDThh:mm:ss[+-]hh:mm`
   */
  createdAtGe?: any | undefined;
  /**
   * This query parameter specifies the upper bound of the stream creation
   *
   * @remarks
   * time as a search criterion. Only streams created before the specified
   * date and time are included in the results. The following value formats
   * are accepted:
   *
   * - `YYYY-MM-DD`
   * - `YYYY-MM-DD[+-]hh:mm`
   * - `YYYY-MM-DDThh:mm`
   * - `YYYY-MM-DDThh:mmZ`
   * - `YYYY-MM-DDThh:mm[+-]hh:mm`
   * - `YYYY-MM-DDThh:mm:ss`
   * - `YYYY-MM-DDThh:mm:ssZ`
   * - `YYYY-MM-DDThh:mm:ss[+-]hh:mm`
   */
  createdAtLt?: any | undefined;
  /**
   * This query parameter specifies the stream status as a search criterion.
   *
   * @remarks
   * The allowed values are `enabled`, `paused`, and `disabled`.
   */
  status?: QueryParamStatus | undefined;
  /**
   * This query parameter specifies the maximum number of streams to include
   *
   * @remarks
   * in the search results. If omitted, the default value is `50`. Valid
   * values range from `1` to `200`, inclusive.
   */
  limit?: any | undefined;
};

export const GetSsfTransmitterTransmitterIdStreamListNotFoundStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetSsfTransmitterTransmitterIdStreamListNotFoundStatus = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdStreamListNotFoundStatus
>;

export type GetSsfTransmitterTransmitterIdStreamListNotFoundResult = {
  status?: GetSsfTransmitterTransmitterIdStreamListNotFoundStatus | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

export const GetSsfTransmitterTransmitterIdStreamListResultStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetSsfTransmitterTransmitterIdStreamListResultStatus = OpenEnum<
  typeof GetSsfTransmitterTransmitterIdStreamListResultStatus
>;

export type GetSsfTransmitterTransmitterIdStreamListResult = {
  status?: GetSsfTransmitterTransmitterIdStreamListResultStatus | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

/**
 * This is the status of the stream. The value is one of `enabled`, `paused`, or `disabled`.
 *
 * @remarks
 */
export const StreamStatus = {
  Enabled: "enabled",
  Paused: "paused",
  Disabled: "disabled",
} as const;
/**
 * This is the status of the stream. The value is one of `enabled`, `paused`, or `disabled`.
 *
 * @remarks
 */
export type StreamStatus = OpenEnum<typeof StreamStatus>;

export type GetSsfTransmitterTransmitterIdStreamListStream = {
  /**
   * This is the primary key of the record representing the stream.
   *
   * @remarks
   */
  id?: any | undefined;
  /**
   * This is the stream ID that was automatically assigned when the stream was created.
   *
   * @remarks
   */
  streamId?: any | undefined;
  /**
   * This is the date and time when the stream was created. The format is `YYYY-MM-DDThh:mm:ss`.
   *
   * @remarks
   */
  createdAt?: any | undefined;
  /**
   * This is the status of the stream. The value is one of `enabled`, `paused`, or `disabled`.
   *
   * @remarks
   */
  status?: StreamStatus | undefined;
  /**
   * This is the description of the stream.
   *
   * @remarks
   */
  description?: any | undefined;
};

/**
 * Streams were retrieved successfully.
 */
export type GetSsfTransmitterTransmitterIdStreamListResponseBody = {
  result?: GetSsfTransmitterTransmitterIdStreamListResult | undefined;
  streams?: Array<GetSsfTransmitterTransmitterIdStreamListStream> | undefined;
  nextCursor?: any | undefined;
};

export type GetSsfTransmitterTransmitterIdStreamListResponse = {
  headers: { [k: string]: Array<string> };
  result: GetSsfTransmitterTransmitterIdStreamListResponseBody;
};

/** @internal */
export const QueryParamStatus$outboundSchema: z.ZodMiniEnum<
  typeof QueryParamStatus
> = z.enum(QueryParamStatus);

/** @internal */
export type GetSsfTransmitterTransmitterIdStreamListRequest$Outbound = {
  "x-fapi-interaction-id"?: any | undefined;
  pretty: any;
  transmitter_id: any;
  cursor?: any | undefined;
  client_id?: any | undefined;
  created_at_ge?: any | undefined;
  created_at_lt?: any | undefined;
  status?: string | undefined;
  limit: any;
};

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListRequest$outboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamListRequest$Outbound,
    GetSsfTransmitterTransmitterIdStreamListRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      pretty: z.any(),
      transmitterId: z.any(),
      cursor: z.optional(z.any()),
      clientId: z.optional(z.any()),
      createdAtGe: z.optional(z.any()),
      createdAtLt: z.optional(z.any()),
      status: z.optional(QueryParamStatus$outboundSchema),
      limit: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
        clientId: "client_id",
        createdAtGe: "created_at_ge",
        createdAtLt: "created_at_lt",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamListRequestToJSON(
  getSsfTransmitterTransmitterIdStreamListRequest:
    GetSsfTransmitterTransmitterIdStreamListRequest,
): string {
  return JSON.stringify(
    GetSsfTransmitterTransmitterIdStreamListRequest$outboundSchema.parse(
      getSsfTransmitterTransmitterIdStreamListRequest,
    ),
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamListNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    GetSsfTransmitterTransmitterIdStreamListNotFoundStatus,
  );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListNotFoundResult$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamListNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      GetSsfTransmitterTransmitterIdStreamListNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function getSsfTransmitterTransmitterIdStreamListNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamListNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamListNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamListNotFoundResult' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListResultStatus$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdStreamListResultStatus, unknown> =
    openEnums.inboundSchema(
      GetSsfTransmitterTransmitterIdStreamListResultStatus,
    );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListResult$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdStreamListResult, unknown> = z
    .object({
      status: types.optional(
        GetSsfTransmitterTransmitterIdStreamListResultStatus$inboundSchema,
      ),
      code: types.optional(z.any()),
      message: types.optional(z.any()),
    });

export function getSsfTransmitterTransmitterIdStreamListResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamListResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamListResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamListResult' from JSON`,
  );
}

/** @internal */
export const StreamStatus$inboundSchema: z.ZodMiniType<StreamStatus, unknown> =
  openEnums.inboundSchema(StreamStatus);

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListStream$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdStreamListStream, unknown> = z
    .pipe(
      z.object({
        id: types.optional(z.any()),
        stream_id: types.optional(z.any()),
        created_at: types.optional(z.any()),
        status: types.optional(StreamStatus$inboundSchema),
        description: types.optional(z.any()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "stream_id": "streamId",
          "created_at": "createdAt",
        });
      }),
    );

export function getSsfTransmitterTransmitterIdStreamListStreamFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamListStream,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamListStream$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamListStream' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListResponseBody$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdStreamListResponseBody, unknown> =
    z.pipe(
      z.object({
        result: types.optional(z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamListResult$inboundSchema
        )),
        streams: types.optional(z.array(z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamListStream$inboundSchema
        ))),
        next_cursor: types.optional(z.any()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "next_cursor": "nextCursor",
        });
      }),
    );

export function getSsfTransmitterTransmitterIdStreamListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamListResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamListResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamListResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamListResponse$inboundSchema:
  z.ZodMiniType<GetSsfTransmitterTransmitterIdStreamListResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamListResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getSsfTransmitterTransmitterIdStreamListResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamListResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamListResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamListResponse' from JSON`,
  );
}
