/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetProbeLivenessRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: string | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: boolean | undefined;
};

export const GetProbeLivenessStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetProbeLivenessStatus = OpenEnum<typeof GetProbeLivenessStatus>;

export type GetProbeLivenessResult = {
  status?: GetProbeLivenessStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * A successful response indicating that this web application is alive.
 *
 * @remarks
 */
export type GetProbeLivenessResponseBody = {
  result?: GetProbeLivenessResult | undefined;
};

export type GetProbeLivenessResponse = {
  headers: { [k: string]: Array<string> };
  result: GetProbeLivenessResponseBody;
};

/** @internal */
export type GetProbeLivenessRequest$Outbound = {
  "x-fapi-interaction-id"?: string | undefined;
  pretty: boolean;
};

/** @internal */
export const GetProbeLivenessRequest$outboundSchema: z.ZodMiniType<
  GetProbeLivenessRequest$Outbound,
  GetProbeLivenessRequest
> = z.pipe(
  z.object({
    xFapiInteractionId: z.optional(z.string()),
    pretty: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      xFapiInteractionId: "x-fapi-interaction-id",
    });
  }),
);

export function getProbeLivenessRequestToJSON(
  getProbeLivenessRequest: GetProbeLivenessRequest,
): string {
  return JSON.stringify(
    GetProbeLivenessRequest$outboundSchema.parse(getProbeLivenessRequest),
  );
}

/** @internal */
export const GetProbeLivenessStatus$inboundSchema: z.ZodMiniType<
  GetProbeLivenessStatus,
  unknown
> = openEnums.inboundSchema(GetProbeLivenessStatus);

/** @internal */
export const GetProbeLivenessResult$inboundSchema: z.ZodMiniType<
  GetProbeLivenessResult,
  unknown
> = z.object({
  status: types.optional(GetProbeLivenessStatus$inboundSchema),
  code: types.optional(types.string()),
  message: types.optional(types.string()),
});

export function getProbeLivenessResultFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeLivenessResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeLivenessResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeLivenessResult' from JSON`,
  );
}

/** @internal */
export const GetProbeLivenessResponseBody$inboundSchema: z.ZodMiniType<
  GetProbeLivenessResponseBody,
  unknown
> = z.object({
  result: types.optional(z.lazy(() => GetProbeLivenessResult$inboundSchema)),
});

export function getProbeLivenessResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeLivenessResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeLivenessResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeLivenessResponseBody' from JSON`,
  );
}

/** @internal */
export const GetProbeLivenessResponse$inboundSchema: z.ZodMiniType<
  GetProbeLivenessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetProbeLivenessResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getProbeLivenessResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeLivenessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeLivenessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeLivenessResponse' from JSON`,
  );
}
