/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetProbeReadinessRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: any | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: any | undefined;
};

export const GetProbeReadinessStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetProbeReadinessStatus = OpenEnum<typeof GetProbeReadinessStatus>;

export type GetProbeReadinessResult = {
  status?: GetProbeReadinessStatus | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

/**
 * A successful response indicating that this web application is ready.
 *
 * @remarks
 */
export type GetProbeReadinessResponseBody = {
  result?: GetProbeReadinessResult | undefined;
};

export type GetProbeReadinessResponse = {
  headers: { [k: string]: Array<string> };
  result: GetProbeReadinessResponseBody;
};

/** @internal */
export type GetProbeReadinessRequest$Outbound = {
  "x-fapi-interaction-id"?: any | undefined;
  pretty: any;
};

/** @internal */
export const GetProbeReadinessRequest$outboundSchema: z.ZodMiniType<
  GetProbeReadinessRequest$Outbound,
  GetProbeReadinessRequest
> = z.pipe(
  z.object({
    xFapiInteractionId: z.optional(z.any()),
    pretty: z.any(),
  }),
  z.transform((v) => {
    return remap$(v, {
      xFapiInteractionId: "x-fapi-interaction-id",
    });
  }),
);

export function getProbeReadinessRequestToJSON(
  getProbeReadinessRequest: GetProbeReadinessRequest,
): string {
  return JSON.stringify(
    GetProbeReadinessRequest$outboundSchema.parse(getProbeReadinessRequest),
  );
}

/** @internal */
export const GetProbeReadinessStatus$inboundSchema: z.ZodMiniType<
  GetProbeReadinessStatus,
  unknown
> = openEnums.inboundSchema(GetProbeReadinessStatus);

/** @internal */
export const GetProbeReadinessResult$inboundSchema: z.ZodMiniType<
  GetProbeReadinessResult,
  unknown
> = z.object({
  status: types.optional(GetProbeReadinessStatus$inboundSchema),
  code: types.optional(z.any()),
  message: types.optional(z.any()),
});

export function getProbeReadinessResultFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeReadinessResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeReadinessResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeReadinessResult' from JSON`,
  );
}

/** @internal */
export const GetProbeReadinessResponseBody$inboundSchema: z.ZodMiniType<
  GetProbeReadinessResponseBody,
  unknown
> = z.object({
  result: types.optional(z.lazy(() => GetProbeReadinessResult$inboundSchema)),
});

export function getProbeReadinessResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeReadinessResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeReadinessResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeReadinessResponseBody' from JSON`,
  );
}

/** @internal */
export const GetProbeReadinessResponse$inboundSchema: z.ZodMiniType<
  GetProbeReadinessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetProbeReadinessResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getProbeReadinessResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProbeReadinessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProbeReadinessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProbeReadinessResponse' from JSON`,
  );
}
