/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: any | undefined;
  /**
   * The transmitter ID.
   *
   * @remarks
   */
  transmitterId: any;
  /**
   * The stream ID.
   *
   * @remarks
   */
  streamId: any;
  /**
   * The JTI of the event.
   *
   * @remarks
   */
  eventJti: any;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: any | undefined;
};

export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus =
  {
    Success: "success",
    Failure: "failure",
    BadRequest: "bad_request",
    Unauthorized: "unauthorized",
    Forbidden: "forbidden",
    NotFound: "not_found",
    Conflict: "conflict",
    ServerError: "server_error",
    ServiceUnavailable: "service_unavailable",
  } as const;
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus =
  OpenEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus
  >;

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult =
  {
    status?:
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus
      | undefined;
    code?: any | undefined;
    message?: any | undefined;
  };

export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus =
  OpenEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus
  >;

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult = {
  status?:
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus
    | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases =
  {
    Aliases: "aliases",
  } as const;
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases =
  ClosedEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases
  >;

/**
 * The subject identifier with the `uri` format as defined in [Section 3.2.7. Uniform Resource Identifier (URI) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.7) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9 =
  {
    format: "uri";
    uri: any;
  };

/**
 * The subject identifier with the `saml_assertion_id` format as defined in [Section 3.5.2. SAML Assertion ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.2) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8 =
  {
    format: "saml_assertion_id";
    issuer: any;
    assertionId: any;
  };

/**
 * The subject identifier with the `phone_number` format as defined in [Section 3.2.5. Phone Number Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.5) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7 =
  {
    format: "phone_number";
    phoneNumber: any;
  };

/**
 * The subject identifier with the `opaque` format as defined in [Section 3.2.4. Opaque Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.4) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6 =
  {
    format: "opaque";
    id: any;
  };

/**
 * The subject identifier with the `jwt_id` format as defined in [Section 3.5.1. JWT ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.1) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5 =
  {
    format: "jwt_id";
    iss: any;
    jti: any;
  };

/**
 * The subject identifier with the `iss_sub` format as defined in [Section 3.2.3. Issuer and Subject Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.3) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4 =
  {
    format: "iss_sub";
    iss: any;
    sub: any;
  };

/**
 * The subject identifier with the `email` format as defined in [Section 3.2.2. Email Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.2) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3 =
  {
    format: "email";
    email: any;
  };

/**
 * The subject identifier with the `did` format as defined in [Section 3.2.6. Decentralized Identifier (DID) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.6) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2 =
  {
    format: "did";
    url: any;
  };

/**
 * The subject identifier with the `account` format as defined in [Section 3.2.1. Account Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.1) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1 =
  {
    format: "account";
    uri: any;
  };

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion =
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9
  | discriminatedUnionTypes.Unknown<"format">;

/**
 * The subject identifier with the `aliases` format as defined in [Section 3.2.8. Aliases Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.8) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20 = {
  format:
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases;
  identifiers: Array<
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9
    | discriminatedUnionTypes.Unknown<"format">
  >;
};

export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex =
  {
    Complex: "complex",
  } as const;
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex =
  ClosedEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex
  >;

/**
 * The subject identifier with the `uri` format as defined in [Section 3.2.7. Uniform Resource Identifier (URI) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.7) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18 = {
  format: "uri";
  uri: any;
};

/**
 * The subject identifier with the `saml_assertion_id` format as defined in [Section 3.5.2. SAML Assertion ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.2) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17 = {
  format: "saml_assertion_id";
  issuer: any;
  assertionId: any;
};

/**
 * The subject identifier with the `phone_number` format as defined in [Section 3.2.5. Phone Number Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.5) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16 = {
  format: "phone_number";
  phoneNumber: any;
};

/**
 * The subject identifier with the `opaque` format as defined in [Section 3.2.4. Opaque Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.4) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15 = {
  format: "opaque";
  id: any;
};

/**
 * The subject identifier with the `jwt_id` format as defined in [Section 3.5.1. JWT ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.1) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14 = {
  format: "jwt_id";
  iss: any;
  jti: any;
};

/**
 * The subject identifier with the `iss_sub` format as defined in [Section 3.2.3. Issuer and Subject Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.3) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13 = {
  format: "iss_sub";
  iss: any;
  sub: any;
};

/**
 * The subject identifier with the `email` format as defined in [Section 3.2.2. Email Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.2) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12 = {
  format: "email";
  email: any;
};

/**
 * The subject identifier with the `did` format as defined in [Section 3.2.6. Decentralized Identifier (DID) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.6) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11 = {
  format: "did";
  url: any;
};

/**
 * The subject identifier with the `account` format as defined in [Section 3.2.1. Account Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.1) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10 = {
  format: "account";
  uri: any;
};

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2 =
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18
  | discriminatedUnionTypes.Unknown<"format">;

/**
 * The subject identifier with the `complex` format as defined in [Section 3.3. Complex Subject Members](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.3) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19 = {
  format:
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex;
  additionalProperties?: {
    [k: string]:
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18
      | discriminatedUnionTypes.Unknown<"format">;
  } | undefined;
};

/**
 * The subject identifier with the `uri` format as defined in [Section 3.2.7. Uniform Resource Identifier (URI) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.7) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9 = {
  format: "uri";
  uri: any;
};

/**
 * The subject identifier with the `saml_assertion_id` format as defined in [Section 3.5.2. SAML Assertion ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.2) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8 = {
  format: "saml_assertion_id";
  issuer: any;
  assertionId: any;
};

/**
 * The subject identifier with the `phone_number` format as defined in [Section 3.2.5. Phone Number Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.5) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7 = {
  format: "phone_number";
  phoneNumber: any;
};

/**
 * The subject identifier with the `opaque` format as defined in [Section 3.2.4. Opaque Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.4) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6 = {
  format: "opaque";
  id: any;
};

/**
 * The subject identifier with the `jwt_id` format as defined in [Section 3.5.1. JWT ID Subject Identifier Format](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-3.5.1) of [OpenID Shared Signals Framework Specification 1.0](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5 = {
  format: "jwt_id";
  iss: any;
  jti: any;
};

/**
 * The subject identifier with the `iss_sub` format as defined in [Section 3.2.3. Issuer and Subject Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.3) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4 = {
  format: "iss_sub";
  iss: any;
  sub: any;
};

/**
 * The subject identifier with the `email` format as defined in [Section 3.2.2. Email Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.2) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3 = {
  format: "email";
  email: any;
};

/**
 * The subject identifier with the `did` format as defined in [Section 3.2.6. Decentralized Identifier (DID) Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.6) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2 = {
  format: "did";
  url: any;
};

/**
 * The subject identifier with the `account` format as defined in [Section 3.2.1. Account Identifier Format](https://www.rfc-editor.org/rfc/rfc9493.html#section-3.2.1) of [RFC 9493: Subject Identifiers for Security Event Tokens](https://www.rfc-editor.org/rfc/rfc9493.html).
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1 = {
  format: "account";
  uri: any;
};

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1 =
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9
  | discriminatedUnionTypes.Unknown<"format">;

/**
 * The subject identifier associated with the event.
 *
 * @remarks
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3 =
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8
  | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9
  | discriminatedUnionTypes.Unknown<"format">;

/**
 * The event information in the same format as a SET payload. The only difference is that the `iat` property is omitted if the event has not yet been delivered.
 *
 * @remarks
 */
export type Payload = {
  /**
   * The issuer of the security event token. This is the identifier of the transmitter.
   *
   * @remarks
   */
  iss?: any | undefined;
  /**
   * The audience of the security event token. This is the identifier of the receiver.
   *
   * @remarks
   */
  aud?: any | undefined;
  /**
   * The JWT ID of the security event token.
   *
   * @remarks
   */
  jti?: any | undefined;
  /**
   * The issuance time of the security event token. The value is represented as the number of seconds since the Unix epoch.
   *
   * @remarks
   */
  iat?: any | undefined;
  /**
   * The transaction identifier associated with the event.
   *
   * @remarks
   */
  txn?: any | undefined;
  /**
   * The time of event. The value is represents as the number of seconds since the Unix epoch.
   *
   * @remarks
   */
  toe?: any | undefined;
  /**
   * The subject identifier associated with the event.
   *
   * @remarks
   */
  subId?:
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8
    | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9
    | discriminatedUnionTypes.Unknown<"format">
    | undefined;
  /**
   * The event type identifier and its optional parameters.
   *
   * @remarks
   */
  events?: { [k: string]: any } | undefined;
};

/**
 * A value from the IANA "[Security Event Token Error Codes](https://www.iana.org/assignments/secevent/secevent.xhtml#secevent-error-codes)" registry that identifies the error.
 *
 * @remarks
 */
export const Err = {
  InvalidRequest: "invalid_request",
  InvalidKey: "invalid_key",
  InvalidIssuer: "invalid_issuer",
  InvalidAudience: "invalid_audience",
  AuthenticationFailed: "authentication_failed",
  AccessDenied: "access_denied",
} as const;
/**
 * A value from the IANA "[Security Event Token Error Codes](https://www.iana.org/assignments/secevent/secevent.xhtml#secevent-error-codes)" registry that identifies the error.
 *
 * @remarks
 */
export type Err = OpenEnum<typeof Err>;

/**
 * The error information in the same format as an error object defined in [Section 2.6](https://www.rfc-editor.org/rfc/rfc8936.html#section-2.6) of [RFC 8936 Poll-Based Security Event Token (SET) Delivery Using HTTP](https://www.rfc-editor.org/rfc/rfc8936.html).
 *
 * @remarks
 */
export type ErrorT = {
  /**
   * A value from the IANA "[Security Event Token Error Codes](https://www.iana.org/assignments/secevent/secevent.xhtml#secevent-error-codes)" registry that identifies the error.
   *
   * @remarks
   */
  err: Err;
  /**
   * A human-readable string that provides additional diagnostic information.
   *
   * @remarks
   */
  description?: any | undefined;
};

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent = {
  /**
   * The event information in the same format as a SET payload. The only difference is that the `iat` property is omitted if the event has not yet been delivered.
   *
   * @remarks
   */
  payload?: Payload | undefined;
  /**
   * The time at which the event was delivered. If the event has not been delivered yet, this property is omitted or its value is `null`.
   *
   * @remarks
   */
  deliveredAt?: any | undefined;
  /**
   * The time at which the receiver acknowledged receipt of the event. If the receiver has not acknowledged it yet, this property is omitted or its value is `null`.
   *
   * @remarks
   */
  acknowledgedAt?: any | undefined;
  /**
   * The time at which the receiver reported an error about the event. If the receiver has not reported it yet, this property is omitted or its value is `null`.
   *
   * @remarks
   */
  errorReportedAt?: any | undefined;
  /**
   * The error information in the same format as an error object defined in [Section 2.6](https://www.rfc-editor.org/rfc/rfc8936.html#section-2.6) of [RFC 8936 Poll-Based Security Event Token (SET) Delivery Using HTTP](https://www.rfc-editor.org/rfc/rfc8936.html).
   *
   * @remarks
   */
  error?: ErrorT | undefined;
};

/**
 * Successfully retrieved information about the event.
 */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody =
  {
    result?:
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult
      | undefined;
    event?:
      | GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent
      | undefined;
  };

export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody;
  };

/** @internal */
export type GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$Outbound =
  {
    "x-fapi-interaction-id"?: any | undefined;
    transmitter_id: any;
    stream_id: any;
    event_jti: any;
    pretty: any;
  };

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$outboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$Outbound,
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      transmitterId: z.any(),
      streamId: z.any(),
      eventJti: z.any(),
      pretty: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
        streamId: "stream_id",
        eventJti: "event_jti",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequestToJSON(
  getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest:
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest,
): string {
  return JSON.stringify(
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest$outboundSchema
      .parse(getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiRequest),
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus,
  );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiNotFoundResult' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus,
    unknown
  > = openEnums.inboundSchema(
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus,
  );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult,
    unknown
  > = z.object({
    status: types.optional(
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases$inboundSchema:
  z.ZodMiniEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases
  > = z.enum(
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases,
  );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9,
    unknown
  > = z.object({
    format: types.literal("uri"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("saml_assertion_id"),
      issuer: z.any(),
      assertion_id: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "assertion_id": "assertionId",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("phone_number"),
      phone_number: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "phone_number": "phoneNumber",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6,
    unknown
  > = z.object({
    format: types.literal("opaque"),
    id: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5,
    unknown
  > = z.object({
    format: types.literal("jwt_id"),
    iss: z.any(),
    jti: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4,
    unknown
  > = z.object({
    format: types.literal("iss_sub"),
    iss: z.any(),
    sub: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3,
    unknown
  > = z.object({
    format: types.literal("email"),
    email: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2,
    unknown
  > = z.object({
    format: types.literal("did"),
    url: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1,
    unknown
  > = z.object({
    format: types.literal("account"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion,
    unknown
  > = discriminatedUnion("format", {
    account: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1$inboundSchema
    ),
    did: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2$inboundSchema
    ),
    email: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3$inboundSchema
    ),
    iss_sub: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4$inboundSchema
    ),
    jwt_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5$inboundSchema
    ),
    opaque: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6$inboundSchema
    ),
    phone_number: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7$inboundSchema
    ),
    saml_assertion_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8$inboundSchema
    ),
    uri: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9$inboundSchema
    ),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnionFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifierUnion' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20,
    unknown
  > = z.object({
    format:
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatAliases$inboundSchema,
    identifiers: z.array(discriminatedUnion("format", {
      account: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier1$inboundSchema
      ),
      did: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier2$inboundSchema
      ),
      email: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier3$inboundSchema
      ),
      iss_sub: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier4$inboundSchema
      ),
      jwt_id: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier5$inboundSchema
      ),
      opaque: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier6$inboundSchema
      ),
      phone_number: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier7$inboundSchema
      ),
      saml_assertion_id: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier8$inboundSchema
      ),
      uri: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiIdentifier9$inboundSchema
      ),
    })),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex$inboundSchema:
  z.ZodMiniEnum<
    typeof GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex
  > = z.enum(
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex,
  );

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18,
    unknown
  > = z.object({
    format: types.literal("uri"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("saml_assertion_id"),
      issuer: z.any(),
      assertion_id: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "assertion_id": "assertionId",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("phone_number"),
      phone_number: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "phone_number": "phoneNumber",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15,
    unknown
  > = z.object({
    format: types.literal("opaque"),
    id: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14,
    unknown
  > = z.object({
    format: types.literal("jwt_id"),
    iss: z.any(),
    jti: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13,
    unknown
  > = z.object({
    format: types.literal("iss_sub"),
    iss: z.any(),
    sub: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12,
    unknown
  > = z.object({
    format: types.literal("email"),
    email: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11,
    unknown
  > = z.object({
    format: types.literal("did"),
    url: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10,
    unknown
  > = z.object({
    format: types.literal("account"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2,
    unknown
  > = discriminatedUnion("format", {
    account: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10$inboundSchema
    ),
    did: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11$inboundSchema
    ),
    email: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12$inboundSchema
    ),
    iss_sub: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13$inboundSchema
    ),
    jwt_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14$inboundSchema
    ),
    opaque: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15$inboundSchema
    ),
    phone_number: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16$inboundSchema
    ),
    saml_assertion_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17$inboundSchema
    ),
    uri: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18$inboundSchema
    ),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion2' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19,
    unknown
  > = collectExtraKeys$(
    z.catchall(
      z.object({
        format:
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiFormatComplex$inboundSchema,
      }),
      discriminatedUnion("format", {
        account: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId10$inboundSchema
        ),
        did: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId11$inboundSchema
        ),
        email: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId12$inboundSchema
        ),
        iss_sub: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId13$inboundSchema
        ),
        jwt_id: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId14$inboundSchema
        ),
        opaque: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId15$inboundSchema
        ),
        phone_number: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId16$inboundSchema
        ),
        saml_assertion_id: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId17$inboundSchema
        ),
        uri: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId18$inboundSchema
        ),
      }),
    ),
    "additionalProperties",
    true,
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9,
    unknown
  > = z.object({
    format: types.literal("uri"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("saml_assertion_id"),
      issuer: z.any(),
      assertion_id: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "assertion_id": "assertionId",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7,
    unknown
  > = z.pipe(
    z.object({
      format: types.literal("phone_number"),
      phone_number: z.any(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "phone_number": "phoneNumber",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6,
    unknown
  > = z.object({
    format: types.literal("opaque"),
    id: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5,
    unknown
  > = z.object({
    format: types.literal("jwt_id"),
    iss: z.any(),
    jti: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4,
    unknown
  > = z.object({
    format: types.literal("iss_sub"),
    iss: z.any(),
    sub: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3,
    unknown
  > = z.object({
    format: types.literal("email"),
    email: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2,
    unknown
  > = z.object({
    format: types.literal("did"),
    url: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1,
    unknown
  > = z.object({
    format: types.literal("account"),
    uri: z.any(),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1,
    unknown
  > = discriminatedUnion("format", {
    account: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1$inboundSchema
    ),
    did: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2$inboundSchema
    ),
    email: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3$inboundSchema
    ),
    iss_sub: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4$inboundSchema
    ),
    jwt_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5$inboundSchema
    ),
    opaque: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6$inboundSchema
    ),
    phone_number: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7$inboundSchema
    ),
    saml_assertion_id: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8$inboundSchema
    ),
    uri: z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9$inboundSchema
    ),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion1' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3,
    unknown
  > = smartUnion([
    z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20$inboundSchema
    ),
    z.lazy(() =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19$inboundSchema
    ),
    discriminatedUnion("format", {
      account: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1$inboundSchema
      ),
      did: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2$inboundSchema
      ),
      email: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3$inboundSchema
      ),
      iss_sub: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4$inboundSchema
      ),
      jwt_id: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5$inboundSchema
      ),
      opaque: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6$inboundSchema
      ),
      phone_number: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7$inboundSchema
      ),
      saml_assertion_id: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8$inboundSchema
      ),
      uri: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9$inboundSchema
      ),
    }),
  ]);

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3FromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubIdUnion3' from JSON`,
  );
}

/** @internal */
export const Payload$inboundSchema: z.ZodMiniType<Payload, unknown> = z.pipe(
  z.object({
    iss: types.optional(z.any()),
    aud: types.optional(z.any()),
    jti: types.optional(z.any()),
    iat: types.optional(z.any()),
    txn: types.optional(z.any()),
    toe: types.optional(z.any()),
    sub_id: types.optional(smartUnion([
      z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId20$inboundSchema
      ),
      z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId19$inboundSchema
      ),
      discriminatedUnion("format", {
        account: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId1$inboundSchema
        ),
        did: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId2$inboundSchema
        ),
        email: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId3$inboundSchema
        ),
        iss_sub: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId4$inboundSchema
        ),
        jwt_id: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId5$inboundSchema
        ),
        opaque: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId6$inboundSchema
        ),
        phone_number: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId7$inboundSchema
        ),
        saml_assertion_id: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId8$inboundSchema
        ),
        uri: z.lazy(() =>
          GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiSubId9$inboundSchema
        ),
      }),
    ])),
    events: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sub_id": "subId",
    });
  }),
);

export function payloadFromJSON(
  jsonString: string,
): SafeParseResult<Payload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payload' from JSON`,
  );
}

/** @internal */
export const Err$inboundSchema: z.ZodMiniType<Err, unknown> = openEnums
  .inboundSchema(Err);

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  err: Err$inboundSchema,
  description: types.optional(z.any()),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent,
    unknown
  > = z.pipe(
    z.object({
      payload: types.optional(z.lazy(() => Payload$inboundSchema)),
      delivered_at: types.optional(z.any()),
      acknowledged_at: types.optional(z.any()),
      error_reported_at: types.optional(z.any()),
      error: types.optional(z.lazy(() => ErrorT$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "delivered_at": "deliveredAt",
        "acknowledged_at": "acknowledgedAt",
        "error_reported_at": "errorReportedAt",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEventFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResult$inboundSchema
      ),
    ),
    event: types.optional(
      z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiEvent$inboundSchema
      ),
    ),
  });

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse$inboundSchema:
  z.ZodMiniType<
    GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetSsfTransmitterTransmitterIdStreamStreamIdEventEventJtiResponse' from JSON`,
  );
}
