/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions = {
  /**
   * This boolean flag indicates whether to format the message body of the forwarded response in a human-friendly way when it's in JSON format.
   *
   * @remarks
   */
  pretty?: any | undefined;
  /**
   * The condition that the access token's scope must satisfy.
   *
   * @remarks
   *
   * The condition can range from a simple single string to more complex
   * structures that combine operators such as `and`, `or`, and `matches`.
   *
   * When the condition is a single string, the access token must include
   * a scope with the specified name:
   *
   * ```
   * "scope1"
   * ```
   *
   * When the condition is a list of strings, the access token must include
   * all of the scopes listed:
   *
   * ```
   * ["scope1", "scope2"]
   * ```
   *
   * A logical AND can be represented using a JSON object with the `and`
   * property with a list of conditions as its value:
   *
   * ```
   * {"and": ["scope1", "scope2"]}
   * ```
   *
   * Likewise, a logical OR can be represented using a JSON object with the
   * `or` property with a list of conditions as its value:
   *
   * ```
   * {"or": ["scope1", "scope2"]}
   * ```
   *
   * More complex conditions can be constructed by combining the `and` and
   * `or` operators:
   *
   * ```
   * {
   *   "or": [
   *     {"and": ["scope1", "scope2"]},
   *     {"and": ["scope3", "scope4"]}
   *   ]
   * }
   * ```
   *
   * The `matches` operator can be used to require that the access token
   * include a scope matching the specified regular expression:
   *
   * ```
   * {"matches": "^.*e1$"}
   * ```
   *
   * The following is a complex example that combines all of the mechanisms
   * introduced so far.
   *
   * ```
   * {
   *   "or": [
   *     {
   *       "and": ["scope1", "scope3"]
   *     }
   *   ],
   *   {
   *     "or": [
   *       "scope4",
   *       ["scope2", "scope3"],
   *       {
   *         "matches": "^.*e1$"
   *       }
   *     ]
   *   }
   * }
   * ```
   *
   * If the access token only has the scopes `scope1` and `scope2`, the
   * above scope condition evaluates to true and access to the resource
   * is granted. (This is because the regular expression `^.*e1$` in the
   * condition matches `scope1`, causing the overall condition to evaluate
   * to true.)
   */
  scopeCondition?: any | undefined;
};

/**
 * The original HTTP request that the internet-facing endpoint has received.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody =
  {
    /**
     * The HTTP method such as `GET`.
     *
     * @remarks
     * Be aware that HTTP method names are case sensitive; although standardized ones ([IANA: HTTP Method Registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml)) are defined in all-uppercase US-ASCII letters. See [Section 9](https://www.rfc-editor.org/rfc/rfc9110.html#section-9 "9. Methods") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     * The case sensitivity affects the validation of DPoP proof, which includes the HTTP method as the value of the `htm` claim ([Section 4.2](https://www.rfc-editor.org/rfc/rfc9449.html#section-4.2 "4.2. DPoP Proof JWT Syntax") of [RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)")).
     */
    method: any;
    /**
     * The target URI, an absolute URL including the query component, if any.
     *
     * @remarks
     * See [Section 7.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.1 "7.1. Determining the Target Resource") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     */
    uri: any;
    /**
     * HTTP headers.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value. HTTP header names are case-insensitive.
     * If the original HTTP request contains the following HTTP headers, include them in this `headers` array:
     *
     *   - `Authorization`
     *   - `Content-Digest`
     *   - `DPoP`
     *   - `Signature`
     *   - `Signature-Input`
     *   - `x-fapi-interaction-id`
     */
    headers?: Array<Array<any>> | undefined;
    /**
     * The message body.
     *
     * @remarks
     */
    body?: any | undefined;
    /**
     * The client's X.509 certificate used in the mutual-TLS connection between the internet-facing endpoint and the endpoint accessor.
     *
     * @remarks
     * This value is referenced when the access token is bound to a specific X.509 certificate using the mechanism defined in [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html "RFC 8705: OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens") (MTLS).
     * The format should be one of the following formats:
     *
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures"))
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures")) without the `BEGIN` and `END` markers
     *   - Byte Sequence ([RFC 8941](https://www.rfc-editor.org/rfc/rfc8941.html "RFC 8941: Structured Field Values for HTTP"))
     *
     * Support for Byte Sequence assumes cases where the value of the `Client-Cert` HTTP header ([RFC 9440](https://www.rfc-editor.org/rfc/rfc9440.html "RFC 9440: Client-Cert HTTP Header Field")) is passed through without any modification.
     */
    certificate?: any | undefined;
    /**
     * The client's IP address.
     *
     * @remarks
     */
    ipAddress?: any | undefined;
  };

/**
 * The message body of requests to delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody = {
  options?:
    | PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions
    | undefined;
  /**
   * The original HTTP request that the internet-facing endpoint has received.
   *
   * @remarks
   */
  request:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody;
};

export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest =
  {
    /**
     * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
     *
     * @remarks
     */
    xFapiInteractionId?: any | undefined;
    /**
     * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
     *
     * @remarks
     */
    pretty?: any | undefined;
    /**
     * The transmitter ID.
     *
     * @remarks
     */
    transmitterId: any;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody
      | undefined;
  };

export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus =
  {
    Success: "success",
    Failure: "failure",
    BadRequest: "bad_request",
    Unauthorized: "unauthorized",
    Forbidden: "forbidden",
    NotFound: "not_found",
    Conflict: "conflict",
    ServerError: "server_error",
    ServiceUnavailable: "service_unavailable",
  } as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus =
  OpenEnum<
    typeof PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus
  >;

export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult =
  {
    status?:
      | PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus
      | undefined;
    code?: any | undefined;
    message?: any | undefined;
  };

export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus =
  OpenEnum<typeof PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus>;

export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult = {
  status?:
    | PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus
    | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

/**
 * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody =
  {
    /**
     * The HTTP status code of the HTTP response.
     *
     * @remarks
     */
    status: any;
    /**
     * HTTP headers that should be included in the HTTP response.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value.
     */
    headers?: Array<Array<any>> | undefined;
    /**
     * The content type of the HTTP response. This parameter is set when the forwarded response contains a message body.
     *
     * @remarks
     */
    contentType?: any | undefined;
    /**
     * The message body of the HTTP response.
     *
     * @remarks
     */
    body?: any | undefined;
  };

/**
 * The message body of responses from delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody = {
  result?:
    | PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult
    | undefined;
  /**
   * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
   *
   * @remarks
   */
  response:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody;
};

export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse =
  {
    headers: { [k: string]: Array<string> };
    result: PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody;
  };

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$Outbound =
  {
    pretty: any;
    scope_condition?: any | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions
  > = z.pipe(
    z.object({
      pretty: z.any(),
      scopeCondition: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        scopeCondition: "scope_condition",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteOptionsToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamDeleteOptions:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamDeleteOptions),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$Outbound =
  {
    method: any;
    uri: any;
    headers?: Array<Array<any>> | undefined;
    body?: any | undefined;
    certificate?: any | undefined;
    ip_address?: any | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody
  > = z.pipe(
    z.object({
      method: z.any(),
      uri: z.any(),
      headers: z.optional(z.array(z.array(z.any()))),
      body: z.optional(z.any()),
      certificate: z.optional(z.any()),
      ipAddress: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        ipAddress: "ip_address",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$outboundSchema
      .parse(
        postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody,
      ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$Outbound =
  {
    options?:
      | PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$Outbound
      | undefined;
    request:
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$Outbound;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody
  > = z.object({
    options: z.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamDeleteOptions$outboundSchema
      ),
    ),
    request: z.lazy(() =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestBody$outboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest$Outbound =
  {
    "x-fapi-interaction-id"?: any | undefined;
    pretty: any;
    transmitter_id: any;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$Outbound
      | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      pretty: z.any(),
      transmitterId: z.any(),
      body: z.optional(z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestBody$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequestToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest:
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamDeleteRequestRequest),
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamDeleteNotFoundResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody,
    unknown
  > = z.object({
    status: z.any(),
    headers: types.optional(z.array(z.array(z.any()))),
    contentType: types.optional(z.any()),
    body: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamDeleteResult$inboundSchema
      ),
    ),
    response: z.lazy(() =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseBody$inboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamDeleteResponseResponse' from JSON`,
  );
}
