/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostSsfTransmitterTransmitterIdDelegateJwksOptions = {
  /**
   * This boolean flag indicates whether to format the message body of the forwarded response in a human-friendly way when it's in JSON format.
   *
   * @remarks
   */
  pretty?: any | undefined;
  /**
   * The condition that the access token's scope must satisfy.
   *
   * @remarks
   *
   * The condition can range from a simple single string to more complex
   * structures that combine operators such as `and`, `or`, and `matches`.
   *
   * When the condition is a single string, the access token must include
   * a scope with the specified name:
   *
   * ```
   * "scope1"
   * ```
   *
   * When the condition is a list of strings, the access token must include
   * all of the scopes listed:
   *
   * ```
   * ["scope1", "scope2"]
   * ```
   *
   * A logical AND can be represented using a JSON object with the `and`
   * property with a list of conditions as its value:
   *
   * ```
   * {"and": ["scope1", "scope2"]}
   * ```
   *
   * Likewise, a logical OR can be represented using a JSON object with the
   * `or` property with a list of conditions as its value:
   *
   * ```
   * {"or": ["scope1", "scope2"]}
   * ```
   *
   * More complex conditions can be constructed by combining the `and` and
   * `or` operators:
   *
   * ```
   * {
   *   "or": [
   *     {"and": ["scope1", "scope2"]},
   *     {"and": ["scope3", "scope4"]}
   *   ]
   * }
   * ```
   *
   * The `matches` operator can be used to require that the access token
   * include a scope matching the specified regular expression:
   *
   * ```
   * {"matches": "^.*e1$"}
   * ```
   *
   * The following is a complex example that combines all of the mechanisms
   * introduced so far.
   *
   * ```
   * {
   *   "or": [
   *     {
   *       "and": ["scope1", "scope3"]
   *     }
   *   ],
   *   {
   *     "or": [
   *       "scope4",
   *       ["scope2", "scope3"],
   *       {
   *         "matches": "^.*e1$"
   *       }
   *     ]
   *   }
   * }
   * ```
   *
   * If the access token only has the scopes `scope1` and `scope2`, the
   * above scope condition evaluates to true and access to the resource
   * is granted. (This is because the regular expression `^.*e1$` in the
   * condition matches `scope1`, causing the overall condition to evaluate
   * to true.)
   */
  scopeCondition?: any | undefined;
};

/**
 * The original HTTP request that the internet-facing endpoint has received.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody = {
  /**
   * The HTTP method such as `GET`.
   *
   * @remarks
   * Be aware that HTTP method names are case sensitive; although standardized ones ([IANA: HTTP Method Registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml)) are defined in all-uppercase US-ASCII letters. See [Section 9](https://www.rfc-editor.org/rfc/rfc9110.html#section-9 "9. Methods") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
   * The case sensitivity affects the validation of DPoP proof, which includes the HTTP method as the value of the `htm` claim ([Section 4.2](https://www.rfc-editor.org/rfc/rfc9449.html#section-4.2 "4.2. DPoP Proof JWT Syntax") of [RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)")).
   */
  method: any;
  /**
   * The target URI, an absolute URL including the query component, if any.
   *
   * @remarks
   * See [Section 7.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.1 "7.1. Determining the Target Resource") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
   */
  uri: any;
  /**
   * HTTP headers.
   *
   * @remarks
   * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value. HTTP header names are case-insensitive.
   * If the original HTTP request contains the following HTTP headers, include them in this `headers` array:
   *
   *   - `Authorization`
   *   - `Content-Digest`
   *   - `DPoP`
   *   - `Signature`
   *   - `Signature-Input`
   *   - `x-fapi-interaction-id`
   */
  headers?: Array<Array<any>> | undefined;
  /**
   * The message body.
   *
   * @remarks
   */
  body?: any | undefined;
  /**
   * The client's X.509 certificate used in the mutual-TLS connection between the internet-facing endpoint and the endpoint accessor.
   *
   * @remarks
   * This value is referenced when the access token is bound to a specific X.509 certificate using the mechanism defined in [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html "RFC 8705: OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens") (MTLS).
   * The format should be one of the following formats:
   *
   *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures"))
   *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures")) without the `BEGIN` and `END` markers
   *   - Byte Sequence ([RFC 8941](https://www.rfc-editor.org/rfc/rfc8941.html "RFC 8941: Structured Field Values for HTTP"))
   *
   * Support for Byte Sequence assumes cases where the value of the `Client-Cert` HTTP header ([RFC 9440](https://www.rfc-editor.org/rfc/rfc9440.html "RFC 9440: Client-Cert HTTP Header Field")) is passed through without any modification.
   */
  certificate?: any | undefined;
  /**
   * The client's IP address.
   *
   * @remarks
   */
  ipAddress?: any | undefined;
};

/**
 * The message body of requests to delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateJwksRequestBody = {
  options?: PostSsfTransmitterTransmitterIdDelegateJwksOptions | undefined;
  /**
   * The original HTTP request that the internet-facing endpoint has received.
   *
   * @remarks
   */
  request: PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody;
};

export type PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: any | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: any | undefined;
  /**
   * The transmitter ID.
   *
   * @remarks
   */
  transmitterId: any;
  body?: PostSsfTransmitterTransmitterIdDelegateJwksRequestBody | undefined;
};

export const PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus =
  OpenEnum<typeof PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus>;

export type PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult = {
  status?:
    | PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus
    | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

export const PostSsfTransmitterTransmitterIdDelegateJwksStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateJwksStatus = OpenEnum<
  typeof PostSsfTransmitterTransmitterIdDelegateJwksStatus
>;

export type PostSsfTransmitterTransmitterIdDelegateJwksResult = {
  status?: PostSsfTransmitterTransmitterIdDelegateJwksStatus | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

/**
 * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody = {
  /**
   * The HTTP status code of the HTTP response.
   *
   * @remarks
   */
  status: any;
  /**
   * HTTP headers that should be included in the HTTP response.
   *
   * @remarks
   * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value.
   */
  headers?: Array<Array<any>> | undefined;
  /**
   * The content type of the HTTP response. This parameter is set when the forwarded response contains a message body.
   *
   * @remarks
   */
  contentType?: any | undefined;
  /**
   * The message body of the HTTP response.
   *
   * @remarks
   */
  body?: any | undefined;
};

/**
 * The message body of responses from delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateJwksResponseBody = {
  result?: PostSsfTransmitterTransmitterIdDelegateJwksResult | undefined;
  /**
   * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
   *
   * @remarks
   */
  response: PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody;
};

export type PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse = {
  headers: { [k: string]: Array<string> };
  result: PostSsfTransmitterTransmitterIdDelegateJwksResponseBody;
};

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateJwksOptions$Outbound = {
  pretty: any;
  scope_condition?: any | undefined;
};

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksOptions$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksOptions$Outbound,
    PostSsfTransmitterTransmitterIdDelegateJwksOptions
  > = z.pipe(
    z.object({
      pretty: z.any(),
      scopeCondition: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        scopeCondition: "scope_condition",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateJwksOptionsToJSON(
  postSsfTransmitterTransmitterIdDelegateJwksOptions:
    PostSsfTransmitterTransmitterIdDelegateJwksOptions,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateJwksOptions$outboundSchema.parse(
      postSsfTransmitterTransmitterIdDelegateJwksOptions,
    ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$Outbound =
  {
    method: any;
    uri: any;
    headers?: Array<Array<any>> | undefined;
    body?: any | undefined;
    certificate?: any | undefined;
    ip_address?: any | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody
  > = z.pipe(
    z.object({
      method: z.any(),
      uri: z.any(),
      headers: z.optional(z.array(z.array(z.any()))),
      body: z.optional(z.any()),
      certificate: z.optional(z.any()),
      ipAddress: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        ipAddress: "ip_address",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateJwksRequestRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody:
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$Outbound = {
  options?:
    | PostSsfTransmitterTransmitterIdDelegateJwksOptions$Outbound
    | undefined;
  request:
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$Outbound;
};

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateJwksRequestBody
  > = z.object({
    options: z.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateJwksOptions$outboundSchema
      ),
    ),
    request: z.lazy(() =>
      PostSsfTransmitterTransmitterIdDelegateJwksRequestRequestBody$outboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateJwksRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateJwksRequestBody:
    PostSsfTransmitterTransmitterIdDelegateJwksRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$outboundSchema.parse(
      postSsfTransmitterTransmitterIdDelegateJwksRequestBody,
    ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest$Outbound =
  {
    "x-fapi-interaction-id"?: any | undefined;
    pretty: any;
    transmitter_id: any;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$Outbound
      | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest$Outbound,
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      pretty: z.any(),
      transmitterId: z.any(),
      body: z.optional(z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateJwksRequestBody$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateJwksRequestRequestToJSON(
  postSsfTransmitterTransmitterIdDelegateJwksRequestRequest:
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateJwksRequestRequest$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateJwksRequestRequest),
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateJwksNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateJwksNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateJwksNotFoundResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksStatus$inboundSchema:
  z.ZodMiniType<PostSsfTransmitterTransmitterIdDelegateJwksStatus, unknown> =
    openEnums.inboundSchema(PostSsfTransmitterTransmitterIdDelegateJwksStatus);

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksResult$inboundSchema:
  z.ZodMiniType<PostSsfTransmitterTransmitterIdDelegateJwksResult, unknown> = z
    .object({
      status: types.optional(
        PostSsfTransmitterTransmitterIdDelegateJwksStatus$inboundSchema,
      ),
      code: types.optional(z.any()),
      message: types.optional(z.any()),
    });

export function postSsfTransmitterTransmitterIdDelegateJwksResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateJwksResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateJwksResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateJwksResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody,
    unknown
  > = z.object({
    status: z.any(),
    headers: types.optional(z.array(z.array(z.any()))),
    contentType: types.optional(z.any()),
    body: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateJwksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateJwksResult$inboundSchema
      ),
    ),
    response: z.lazy(() =>
      PostSsfTransmitterTransmitterIdDelegateJwksResponseResponseBody$inboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateJwksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateJwksResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateJwksResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateJwksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateJwksResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateJwksResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateJwksResponseResponse' from JSON`,
  );
}
