/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition =
  {};

/**
 * The condition that the access token's scope must satisfy.
 *
 * @remarks
 *
 * The condition can range from a simple single string to more complex
 * structures that combine operators such as `and`, `or`, and `matches`.
 *
 * When the condition is a single string, the access token must include
 * a scope with the specified name:
 *
 * ```
 * "scope1"
 * ```
 *
 * When the condition is a list of strings, the access token must include
 * all of the scopes listed:
 *
 * ```
 * ["scope1", "scope2"]
 * ```
 *
 * A logical AND can be represented using a JSON object with the `and`
 * property with a list of conditions as its value:
 *
 * ```
 * {"and": ["scope1", "scope2"]}
 * ```
 *
 * Likewise, a logical OR can be represented using a JSON object with the
 * `or` property with a list of conditions as its value:
 *
 * ```
 * {"or": ["scope1", "scope2"]}
 * ```
 *
 * More complex conditions can be constructed by combining the `and` and
 * `or` operators:
 *
 * ```
 * {
 *   "or": [
 *     {"and": ["scope1", "scope2"]},
 *     {"and": ["scope3", "scope4"]}
 *   ]
 * }
 * ```
 *
 * The `matches` operator can be used to require that the access token
 * include a scope matching the specified regular expression:
 *
 * ```
 * {"matches": "^.*e1$"}
 * ```
 *
 * The following is a complex example that combines all of the mechanisms
 * introduced so far.
 *
 * ```
 * {
 *   "or": [
 *     {
 *       "and": ["scope1", "scope3"]
 *     }
 *   ],
 *   {
 *     "or": [
 *       "scope4",
 *       ["scope2", "scope3"],
 *       {
 *         "matches": "^.*e1$"
 *       }
 *     ]
 *   }
 * }
 * ```
 *
 * If the access token only has the scopes `scope1` and `scope2`, the
 * above scope condition evaluates to true and access to the resource
 * is granted. (This is because the regular expression `^.*e1$` in the
 * condition matches `scope1`, causing the overall condition to evaluate
 * to true.)
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion =
  | boolean
  | string
  | Array<any>
  | PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition;

export type PostSsfTransmitterTransmitterIdDelegateStreamReadOptions = {
  /**
   * This boolean flag indicates whether to format the message body of the forwarded response in a human-friendly way when it's in JSON format.
   *
   * @remarks
   */
  pretty?: boolean | undefined;
  /**
   * The condition that the access token's scope must satisfy.
   *
   * @remarks
   *
   * The condition can range from a simple single string to more complex
   * structures that combine operators such as `and`, `or`, and `matches`.
   *
   * When the condition is a single string, the access token must include
   * a scope with the specified name:
   *
   * ```
   * "scope1"
   * ```
   *
   * When the condition is a list of strings, the access token must include
   * all of the scopes listed:
   *
   * ```
   * ["scope1", "scope2"]
   * ```
   *
   * A logical AND can be represented using a JSON object with the `and`
   * property with a list of conditions as its value:
   *
   * ```
   * {"and": ["scope1", "scope2"]}
   * ```
   *
   * Likewise, a logical OR can be represented using a JSON object with the
   * `or` property with a list of conditions as its value:
   *
   * ```
   * {"or": ["scope1", "scope2"]}
   * ```
   *
   * More complex conditions can be constructed by combining the `and` and
   * `or` operators:
   *
   * ```
   * {
   *   "or": [
   *     {"and": ["scope1", "scope2"]},
   *     {"and": ["scope3", "scope4"]}
   *   ]
   * }
   * ```
   *
   * The `matches` operator can be used to require that the access token
   * include a scope matching the specified regular expression:
   *
   * ```
   * {"matches": "^.*e1$"}
   * ```
   *
   * The following is a complex example that combines all of the mechanisms
   * introduced so far.
   *
   * ```
   * {
   *   "or": [
   *     {
   *       "and": ["scope1", "scope3"]
   *     }
   *   ],
   *   {
   *     "or": [
   *       "scope4",
   *       ["scope2", "scope3"],
   *       {
   *         "matches": "^.*e1$"
   *       }
   *     ]
   *   }
   * }
   * ```
   *
   * If the access token only has the scopes `scope1` and `scope2`, the
   * above scope condition evaluates to true and access to the resource
   * is granted. (This is because the regular expression `^.*e1$` in the
   * condition matches `scope1`, causing the overall condition to evaluate
   * to true.)
   */
  scopeCondition?:
    | boolean
    | string
    | Array<any>
    | PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition
    | null
    | undefined;
};

/**
 * The original HTTP request that the internet-facing endpoint has received.
 *
 * @remarks
 */
export type DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest =
  {
    /**
     * The HTTP method such as `GET`.
     *
     * @remarks
     * Be aware that HTTP method names are case sensitive; although standardized ones ([IANA: HTTP Method Registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml)) are defined in all-uppercase US-ASCII letters. See [Section 9](https://www.rfc-editor.org/rfc/rfc9110.html#section-9 "9. Methods") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     * The case sensitivity affects the validation of DPoP proof, which includes the HTTP method as the value of the `htm` claim ([Section 4.2](https://www.rfc-editor.org/rfc/rfc9449.html#section-4.2 "4.2. DPoP Proof JWT Syntax") of [RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)")).
     */
    method: string;
    /**
     * The target URI, an absolute URL including the query component, if any.
     *
     * @remarks
     * See [Section 7.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.1 "7.1. Determining the Target Resource") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     */
    uri: string;
    /**
     * HTTP headers.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value. HTTP header names are case-insensitive.
     * If the original HTTP request contains the following HTTP headers, include them in this `headers` array:
     *
     *   - `Authorization`
     *   - `Content-Digest`
     *   - `DPoP`
     *   - `Signature`
     *   - `Signature-Input`
     *   - `x-fapi-interaction-id`
     */
    headers?: Array<Array<string>> | undefined;
    /**
     * The message body.
     *
     * @remarks
     */
    body?: string | undefined;
    /**
     * The client's X.509 certificate used in the mutual-TLS connection between the internet-facing endpoint and the endpoint accessor.
     *
     * @remarks
     * This value is referenced when the access token is bound to a specific X.509 certificate using the mechanism defined in [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html "RFC 8705: OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens") (MTLS).
     * The format should be one of the following formats:
     *
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures"))
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures")) without the `BEGIN` and `END` markers
     *   - Byte Sequence ([RFC 8941](https://www.rfc-editor.org/rfc/rfc8941.html "RFC 8941: Structured Field Values for HTTP"))
     *
     * Support for Byte Sequence assumes cases where the value of the `Client-Cert` HTTP header ([RFC 9440](https://www.rfc-editor.org/rfc/rfc9440.html "RFC 9440: Client-Cert HTTP Header Field")) is passed through without any modification.
     */
    certificate?: string | undefined;
    /**
     * The client's IP address.
     *
     * @remarks
     */
    ipAddress?: string | undefined;
  };

/**
 * The message body of requests to delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody = {
  options?:
    | PostSsfTransmitterTransmitterIdDelegateStreamReadOptions
    | undefined;
  /**
   * The original HTTP request that the internet-facing endpoint has received.
   *
   * @remarks
   */
  request:
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest;
};

export type PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest = {
  /**
   * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
   *
   * @remarks
   */
  xFapiInteractionId?: string | undefined;
  /**
   * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
   *
   * @remarks
   */
  pretty?: boolean | undefined;
  /**
   * The transmitter ID.
   *
   * @remarks
   */
  transmitterId: string;
  body?:
    | PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody
    | undefined;
};

export const PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus =
  OpenEnum<
    typeof PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus
  >;

export type PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult = {
  status?:
    | PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus
    | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

export const PostSsfTransmitterTransmitterIdDelegateStreamReadStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamReadStatus = OpenEnum<
  typeof PostSsfTransmitterTransmitterIdDelegateStreamReadStatus
>;

export type PostSsfTransmitterTransmitterIdDelegateStreamReadResult = {
  status?: PostSsfTransmitterTransmitterIdDelegateStreamReadStatus | undefined;
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
 *
 * @remarks
 */
export type DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse =
  {
    /**
     * The HTTP status code of the HTTP response.
     *
     * @remarks
     */
    status: number;
    /**
     * HTTP headers that should be included in the HTTP response.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value.
     */
    headers?: Array<Array<string>> | undefined;
    /**
     * The content type of the HTTP response. This parameter is set when the forwarded response contains a message body.
     *
     * @remarks
     */
    contentType?: string | undefined;
    /**
     * The message body of the HTTP response.
     *
     * @remarks
     */
    body?: string | undefined;
  };

/**
 * The message body of responses from delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody = {
  result?: PostSsfTransmitterTransmitterIdDelegateStreamReadResult | undefined;
  /**
   * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
   *
   * @remarks
   */
  response:
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse;
};

export type PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse =
  {
    headers: { [k: string]: Array<string> };
    result: PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody;
  };

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$Outbound =
  {};

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition
  > = z.object({});

export function postSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition:
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion$Outbound =
  | boolean
  | string
  | Array<any>
  | PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$Outbound;

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion
  > = smartUnion([
    z.boolean(),
    z.string(),
    z.array(z.any()),
    z.lazy(() =>
      PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$outboundSchema
    ),
  ]);

export function postSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnionToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion:
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion$outboundSchema
      .parse(
        postSsfTransmitterTransmitterIdDelegateStreamReadScopeConditionUnion,
      ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$Outbound =
  {
    pretty: boolean;
    scope_condition?:
      | boolean
      | string
      | Array<any>
      | PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$Outbound
      | null
      | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamReadOptions
  > = z.pipe(
    z.object({
      pretty: z._default(z.boolean(), false),
      scopeCondition: z.optional(
        z.nullable(
          smartUnion([
            z.boolean(),
            z.string(),
            z.array(z.any()),
            z.lazy(() =>
              PostSsfTransmitterTransmitterIdDelegateStreamReadScopeCondition$outboundSchema
            ),
          ]),
        ),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        scopeCondition: "scope_condition",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamReadOptionsToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamReadOptions:
    PostSsfTransmitterTransmitterIdDelegateStreamReadOptions,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamReadOptions),
  );
}

/** @internal */
export type DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$Outbound =
  {
    method: string;
    uri: string;
    headers?: Array<Array<string>> | undefined;
    body?: string | undefined;
    certificate?: string | undefined;
    ip_address?: string | undefined;
  };

/** @internal */
export const DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$outboundSchema:
  z.ZodMiniType<
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$Outbound,
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest
  > = z.pipe(
    z.object({
      method: z.string(),
      uri: z.string(),
      headers: z.optional(z.array(z.array(z.string()))),
      body: z.optional(z.string()),
      certificate: z.optional(z.string()),
      ipAddress: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        ipAddress: "ip_address",
      });
    }),
  );

export function delegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequestToJSON(
  delegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest:
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest,
): string {
  return JSON.stringify(
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$outboundSchema
      .parse(
        delegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest,
      ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$Outbound =
  {
    options?:
      | PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$Outbound
      | undefined;
    request:
      DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$Outbound;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody
  > = z.object({
    options: z.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamReadOptions$outboundSchema
      ),
    ),
    request: z.lazy(() =>
      DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadRequest$outboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamReadRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamReadRequestBody:
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamReadRequestBody),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest$Outbound =
  {
    "x-fapi-interaction-id"?: string | undefined;
    pretty: boolean;
    transmitter_id: string;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$Outbound
      | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.string()),
      pretty: z._default(z.boolean(), false),
      transmitterId: z.string(),
      body: z.optional(z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamReadRequestBody$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamReadRequestRequestToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest:
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamReadRequestRequest),
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundStatus$inboundSchema,
    ),
    code: types.optional(types.string()),
    message: types.optional(types.string()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamReadNotFoundResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamReadStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamReadStatus$inboundSchema,
    ),
    code: types.optional(types.string()),
    message: types.optional(types.string()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamReadResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamReadResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamReadResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamReadResult' from JSON`,
  );
}

/** @internal */
export const DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse$inboundSchema:
  z.ZodMiniType<
    DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse,
    unknown
  > = z.object({
    status: types.number(),
    headers: types.optional(z.array(z.array(types.string()))),
    contentType: types.optional(types.string()),
    body: types.optional(types.string()),
  });

export function delegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamReadResult$inboundSchema
      ),
    ),
    response: z.lazy(() =>
      DelegateStreamsPostSsfTransmitterTransmitterIdDelegateStreamReadResponse$inboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamReadResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamReadResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamReadResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamReadResponseResponse' from JSON`,
  );
}
