/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions = {
  /**
   * This boolean flag indicates whether to format the message body of the forwarded response in a human-friendly way when it's in JSON format.
   *
   * @remarks
   */
  pretty?: any | undefined;
  /**
   * The condition that the access token's scope must satisfy.
   *
   * @remarks
   *
   * The condition can range from a simple single string to more complex
   * structures that combine operators such as `and`, `or`, and `matches`.
   *
   * When the condition is a single string, the access token must include
   * a scope with the specified name:
   *
   * ```
   * "scope1"
   * ```
   *
   * When the condition is a list of strings, the access token must include
   * all of the scopes listed:
   *
   * ```
   * ["scope1", "scope2"]
   * ```
   *
   * A logical AND can be represented using a JSON object with the `and`
   * property with a list of conditions as its value:
   *
   * ```
   * {"and": ["scope1", "scope2"]}
   * ```
   *
   * Likewise, a logical OR can be represented using a JSON object with the
   * `or` property with a list of conditions as its value:
   *
   * ```
   * {"or": ["scope1", "scope2"]}
   * ```
   *
   * More complex conditions can be constructed by combining the `and` and
   * `or` operators:
   *
   * ```
   * {
   *   "or": [
   *     {"and": ["scope1", "scope2"]},
   *     {"and": ["scope3", "scope4"]}
   *   ]
   * }
   * ```
   *
   * The `matches` operator can be used to require that the access token
   * include a scope matching the specified regular expression:
   *
   * ```
   * {"matches": "^.*e1$"}
   * ```
   *
   * The following is a complex example that combines all of the mechanisms
   * introduced so far.
   *
   * ```
   * {
   *   "or": [
   *     {
   *       "and": ["scope1", "scope3"]
   *     }
   *   ],
   *   {
   *     "or": [
   *       "scope4",
   *       ["scope2", "scope3"],
   *       {
   *         "matches": "^.*e1$"
   *       }
   *     ]
   *   }
   * }
   * ```
   *
   * If the access token only has the scopes `scope1` and `scope2`, the
   * above scope condition evaluates to true and access to the resource
   * is granted. (This is because the regular expression `^.*e1$` in the
   * condition matches `scope1`, causing the overall condition to evaluate
   * to true.)
   */
  scopeCondition?: any | undefined;
};

/**
 * The original HTTP request that the internet-facing endpoint has received.
 *
 * @remarks
 */
export type DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest =
  {
    /**
     * The HTTP method such as `GET`.
     *
     * @remarks
     * Be aware that HTTP method names are case sensitive; although standardized ones ([IANA: HTTP Method Registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml)) are defined in all-uppercase US-ASCII letters. See [Section 9](https://www.rfc-editor.org/rfc/rfc9110.html#section-9 "9. Methods") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     * The case sensitivity affects the validation of DPoP proof, which includes the HTTP method as the value of the `htm` claim ([Section 4.2](https://www.rfc-editor.org/rfc/rfc9449.html#section-4.2 "4.2. DPoP Proof JWT Syntax") of [RFC 9449](https://www.rfc-editor.org/rfc/rfc9449.html "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)")).
     */
    method: any;
    /**
     * The target URI, an absolute URL including the query component, if any.
     *
     * @remarks
     * See [Section 7.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.1 "7.1. Determining the Target Resource") of [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html "RFC 9110: HTTP Semantics") for details.
     */
    uri: any;
    /**
     * HTTP headers.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value. HTTP header names are case-insensitive.
     * If the original HTTP request contains the following HTTP headers, include them in this `headers` array:
     *
     *   - `Authorization`
     *   - `Content-Digest`
     *   - `DPoP`
     *   - `Signature`
     *   - `Signature-Input`
     *   - `x-fapi-interaction-id`
     */
    headers?: Array<Array<any>> | undefined;
    /**
     * The message body.
     *
     * @remarks
     */
    body?: any | undefined;
    /**
     * The client's X.509 certificate used in the mutual-TLS connection between the internet-facing endpoint and the endpoint accessor.
     *
     * @remarks
     * This value is referenced when the access token is bound to a specific X.509 certificate using the mechanism defined in [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html "RFC 8705: OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens") (MTLS).
     * The format should be one of the following formats:
     *
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures"))
     *   - PEM ([RFC 7468](https://www.rfc-editor.org/rfc/rfc7468.html "RFC 7468: Textual Encodings of PKIX, PKCS, and CMS Structures")) without the `BEGIN` and `END` markers
     *   - Byte Sequence ([RFC 8941](https://www.rfc-editor.org/rfc/rfc8941.html "RFC 8941: Structured Field Values for HTTP"))
     *
     * Support for Byte Sequence assumes cases where the value of the `Client-Cert` HTTP header ([RFC 9440](https://www.rfc-editor.org/rfc/rfc9440.html "RFC 9440: Client-Cert HTTP Header Field")) is passed through without any modification.
     */
    certificate?: any | undefined;
    /**
     * The client's IP address.
     *
     * @remarks
     */
    ipAddress?: any | undefined;
  };

/**
 * The message body of requests to delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody =
  {
    options?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions
      | undefined;
    /**
     * The original HTTP request that the internet-facing endpoint has received.
     *
     * @remarks
     */
    request:
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest;
  };

export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest =
  {
    /**
     * This header is defined in "[FAPI 1.0 Baseline](https://openid.net/specs/openid-financial-api-part-1-1_0.html)" and "FAPI 2.0 Implementation Advice". If the request includes this header, the response will contain a response header with the same name and the same value. If the request does not include this header, the value of the corresponding response header will be a randomly generated value. This mechanism is designed for tracking communication. When using this header, its value must be a UUID as defined in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html).
     *
     * @remarks
     */
    xFapiInteractionId?: any | undefined;
    /**
     * This query parameter enables pretty-printing when the response content type is JSON. If `pretty=true` (case-insensitive), the response is formatted for readability. If `pretty` is omitted or set to any other value, pretty-printing is disabled.
     *
     * @remarks
     */
    pretty?: any | undefined;
    /**
     * The transmitter ID.
     *
     * @remarks
     */
    transmitterId: any;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody
      | undefined;
  };

export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus =
  {
    Success: "success",
    Failure: "failure",
    BadRequest: "bad_request",
    Unauthorized: "unauthorized",
    Forbidden: "forbidden",
    NotFound: "not_found",
    Conflict: "conflict",
    ServerError: "server_error",
    ServiceUnavailable: "service_unavailable",
  } as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus =
  OpenEnum<
    typeof PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus
  >;

export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult =
  {
    status?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus
      | undefined;
    code?: any | undefined;
    message?: any | undefined;
  };

export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus = {
  Success: "success",
  Failure: "failure",
  BadRequest: "bad_request",
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  Conflict: "conflict",
  ServerError: "server_error",
  ServiceUnavailable: "service_unavailable",
} as const;
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus =
  OpenEnum<
    typeof PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus
  >;

export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult = {
  status?:
    | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus
    | undefined;
  code?: any | undefined;
  message?: any | undefined;
};

/**
 * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
 *
 * @remarks
 */
export type DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse =
  {
    /**
     * The HTTP status code of the HTTP response.
     *
     * @remarks
     */
    status: any;
    /**
     * HTTP headers that should be included in the HTTP response.
     *
     * @remarks
     * Each element of this `headers` array is an array containing two strings: an HTTP header name and its value.
     */
    headers?: Array<Array<any>> | undefined;
    /**
     * The content type of the HTTP response. This parameter is set when the forwarded response contains a message body.
     *
     * @remarks
     */
    contentType?: any | undefined;
    /**
     * The message body of the HTTP response.
     *
     * @remarks
     */
    body?: any | undefined;
  };

/**
 * The message body of responses from delegate APIs.
 *
 * @remarks
 */
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody =
  {
    result?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult
      | undefined;
    /**
     * The HTTP response that the internet-facing endpoint should return to the endpoint accessor.
     *
     * @remarks
     */
    response:
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse;
  };

export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody;
  };

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$Outbound =
  {
    pretty: any;
    scope_condition?: any | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions
  > = z.pipe(
    z.object({
      pretty: z.any(),
      scopeCondition: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        scopeCondition: "scope_condition",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListOptionsToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions:
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$outboundSchema
      .parse(postSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions),
  );
}

/** @internal */
export type DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$Outbound =
  {
    method: any;
    uri: any;
    headers?: Array<Array<any>> | undefined;
    body?: any | undefined;
    certificate?: any | undefined;
    ip_address?: any | undefined;
  };

/** @internal */
export const DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$outboundSchema:
  z.ZodMiniType<
    DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$Outbound,
    DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest
  > = z.pipe(
    z.object({
      method: z.any(),
      uri: z.any(),
      headers: z.optional(z.array(z.array(z.any()))),
      body: z.optional(z.any()),
      certificate: z.optional(z.any()),
      ipAddress: z.optional(z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        ipAddress: "ip_address",
      });
    }),
  );

export function delegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestToJSON(
  delegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest:
    DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest,
): string {
  return JSON.stringify(
    DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$outboundSchema
      .parse(
        delegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest,
      ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$Outbound =
  {
    options?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$Outbound
      | undefined;
    request:
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$Outbound;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody
  > = z.object({
    options: z.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamSubjectListOptions$outboundSchema
      ),
    ),
    request: z.lazy(() =>
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequest$outboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBodyToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody:
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$outboundSchema
      .parse(
        postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody,
      ),
  );
}

/** @internal */
export type PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest$Outbound =
  {
    "x-fapi-interaction-id"?: any | undefined;
    pretty: any;
    transmitter_id: any;
    body?:
      | PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$Outbound
      | undefined;
  };

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest$outboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest$Outbound,
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest
  > = z.pipe(
    z.object({
      xFapiInteractionId: z.optional(z.any()),
      pretty: z.any(),
      transmitterId: z.any(),
      body: z.optional(z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestBody$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        xFapiInteractionId: "x-fapi-interaction-id",
        transmitterId: "transmitter_id",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequestToJSON(
  postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest:
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest,
): string {
  return JSON.stringify(
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest$outboundSchema
      .parse(
        postSsfTransmitterTransmitterIdDelegateStreamSubjectListRequestRequest,
      ),
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamSubjectListNotFoundResult' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus,
    unknown
  > = openEnums.inboundSchema(
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus,
  );

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult,
    unknown
  > = z.object({
    status: types.optional(
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListStatus$inboundSchema,
    ),
    code: types.optional(z.any()),
    message: types.optional(z.any()),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult' from JSON`,
  );
}

/** @internal */
export const DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse$inboundSchema:
  z.ZodMiniType<
    DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse,
    unknown
  > = z.object({
    status: z.any(),
    headers: types.optional(z.array(z.array(z.any()))),
    contentType: types.optional(z.any()),
    body: types.optional(z.any()),
  });

export function delegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody,
    unknown
  > = z.object({
    result: types.optional(
      z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResult$inboundSchema
      ),
    ),
    response: z.lazy(() =>
      DelegateSubjectsPostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponse$inboundSchema
    ),
  });

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody' from JSON`,
  );
}

/** @internal */
export const PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse$inboundSchema:
  z.ZodMiniType<
    PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function postSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostSsfTransmitterTransmitterIdDelegateStreamSubjectListResponseResponse' from JSON`,
  );
}
